// John 1 — English translation & annotations.
// english entry: [text, alignIds, supplied?]

export const CONTENT = {
  1: {
    english: [
      ["In", "g1.1.1"],
      ["the", "g1.1.2", true],
      ["beginning", "g1.1.2"],
      ["was", "g1.1.3"],
      ["the", "g1.1.4"],
      ["Word,", "g1.1.5"],
      ["and", "g1.1.6"],
      ["the", "g1.1.7"],
      ["Word", "g1.1.8"],
      ["was", "g1.1.9"],
      ["with", "g1.1.10"],
      ["God,", "g1.1.11 g1.1.12"],
      ["and", "g1.1.13"],
      ["the", "g1.1.16"],
      ["Word", "g1.1.17"],
      ["was", "g1.1.15"],
      ["God.", "g1.1.14"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.1.5 g1.1.8 g1.1.17", lemma: "λόγος (Logos)",
        title: "Why “the Word” — and why leave it capitalized",
        body: "*Logos* carried an enormous freight of meaning that no single English word captures. In Greek philosophy (Heraclitus, and later the Stoics) it named the rational principle ordering the cosmos. In Hellenistic Judaism — especially Philo of Alexandria — it bridged the transcendent God and the created world. And it reaches back to the Hebrew Scriptures: the *dabar* (word) of the LORD by which the heavens were made (Ps 33:6), and personified *Wisdom* present at creation (Prov 8). John deliberately writes into all of these at once. We keep **“the Word”** (capitalized) rather than “Reason” or a transliterated “Logos”: it preserves the link to speech and self-expression, and to the creative *dabar*, while the capital signals that a title, not a common noun, is meant.",
      },
      {
        kind: "grammar", refs: "g1.1.3 g1.1.9 g1.1.15", lemma: "ἦν (imperfect of εἰμί)",
        title: "Three times “was” — and it matters",
        body: "Each **ἦν** is an *imperfect*, expressing continuous existence in the past: the Word already *was*, with no implied beginning. This is set up deliberately against the aorist **ἐγένετο** (“came to be”) that governs the created order in v. 3 and the incarnation in v. 14. The grammar itself carries the theology: the Word *is not made*.",
      },
      {
        kind: "translation", refs: "g1.1.10 g1.1.11 g1.1.12", lemma: "πρὸς τὸν θεόν",
        title: "“with God” — but a dynamic, face-to-face “with”",
        body: "**πρός** with the accusative is more mobile than the flat English “with.” It suggests orientation *toward* — presence in relationship, almost “face to face with” God. Older renderings tried “the Word was with God” and let context supply the intimacy; some translators reach for “in the presence of.” We keep the plain **“with,”** but the note is where the relational charge lives: the Word is distinct enough to be *toward* God, yet (next clause) is not other than God.",
      },
      {
        kind: "concept", refs: "g1.1.14 g1.1.16 g1.1.17", lemma: "θεὸς ἦν ὁ λόγος",
        title: "The famous clause: “the Word was God”",
        body: "Word order in Greek is free, and John writes **θεὸς ἦν ὁ λόγος** — literally “God was the Word.” Which noun is the subject? The one with the article: **ὁ λόγος**. So the subject is *the Word*, and **θεός** is the predicate, fronted for emphasis (select **Θεὸς** and watch it light up “God” at the *end* of the English line — the alignment shows the reordering). Because the predicate **θεός** is *anarthrous* (no article) and precedes the verb, it is qualitative — it tells us *what* the Word is, sharing the divine nature, without collapsing the Word into the person just called “God” in the previous clause. This is why “the Word was God” is right, and why both “a god” (indefinite) and “the Word was divine” (merely adjectival) miss it: the first denies full deity, the second dilutes it. (Grammarians cite *Colwell’s rule* and, more precisely, the study of qualitative anarthrous predicate nouns.)",
      },
      {
        kind: "p66", refs: "g1.1.12 g1.1.14 g1.1.5 g1.1.8 g1.1.17", lemma: "θεόν / θεός · λόγος",
        title: "What 𝔓⁶⁶ actually shows here — with an honest caveat",
        body: "In 𝔓⁶⁶ the two occurrences of *God* in v. 1 are written as *nomina sacra* — the sacred abbreviations **θ̅ν̅** (θεόν) and **θ̅ς̅** (θεός), each under a horizontal overline — while **λόγος**, “the Word,” is written out *in full* every time and is **not** treated as a sacred name. But candor is owed to the reader: the top of the papyrus’s first page is damaged, and per the IGNTP transcription **all** the θεός forms in vv. 1–2 fall in a *lacuna* and are editorially **supplied** — reconstructed, not legible. So 𝔓⁶⁶ is a witness to the *layout and wording* of these lines, but its famous θ̅ς̅ at “the Word was God” is a scholarly reconstruction of missing text, not ink we can still read. (Date of the codex is itself debated: Martin’s ~200 CE, against later estimates reaching into the 4th century.)",
      },
      {
        kind: "reading", refs: "g1.1.5 g1.14.4 g1.14.13",
        title: "The Word: how to read the Prologue",
        body: "Before John tells a single story he sings an overture — and it makes the boldest claim in the New Testament. **“The Word”** (*Logos*) was already a word thick with meaning: for Greek thinkers, the rational principle ordering the cosmos; for Jewish readers, the *dabar* of God by which the world was made (Gen 1) and the figure of **Wisdom** present at creation (Prov 8). John reaches for all of it — and then does something audacious. That cosmic ordering-principle, he says, **“became flesh”** (v. 14): it has a human face, a village, a name. The eternal reason behind reality is identified with a first-century Galilean who grows tired, weeps, and dies. This is less a proof than a *lens*: the Prologue tells you how to read everything that follows — the carpenter is the Word, and to have met him (“we **beheld his glory**”) is to have met God’s own self-expression. All that comes after is the working-out of a claim already made: God has spoken, and the speech is a person.",
      },
    ],
  },
  2: {
    english: [
      ["He", "g1.2.1"],
      ["was", "g1.2.2"],
      ["in", "g1.2.3"],
      ["the", "g1.2.4", true],
      ["beginning", "g1.2.4"],
      ["with", "g1.2.5"],
      ["God.", "g1.2.6 g1.2.7"],
    ],
    annotations: [
      {
        kind: "grammar", refs: "g1.2.1", lemma: "οὗτος",
        title: "Why restate it? The force of “this one”",
        body: "Verse 2 looks like mere repetition, but **οὗτος** (“this very one”) is emphatic and *resumptive*: it gathers up everything said in v. 1 and pins it to a single subject before the sentence moves on to creation. It forecloses a misreading — that “the Word was God” might describe some later, lesser stage. The one who *was God* and *was with God* is the same one, and was so **ἐν ἀρχῇ**, in the beginning. We render it **“He”** for English flow; the demonstrative weight is noted here.",
      },
    ],
  },
  3: {
    english: [
      ["All", "g1.3.1"],
      ["things", "g1.3.1"],
      ["came", "g1.3.4"],
      ["to", "g1.3.4"],
      ["be", "g1.3.4"],
      ["through", "g1.3.2"],
      ["him,", "g1.3.3"],
      ["and", "g1.3.5"],
      ["apart", "g1.3.6"],
      ["from", "g1.3.6"],
      ["him", "g1.3.7"],
      ["not", "g1.3.9"],
      ["one", "g1.3.10"],
      ["thing", "g1.3.10", true],
      ["came", "g1.3.8"],
      ["to", "g1.3.8"],
      ["be", "g1.3.8"],
      ["that", "g1.3.11"],
      ["has", "g1.3.12"],
      ["come", "g1.3.12"],
      ["to", "g1.3.12"],
      ["be.", "g1.3.12"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.3.4 g1.3.8 g1.3.12", lemma: "ἐγένετο / γέγονεν (γίνομαι)",
        title: "“Came to be” — the hinge of the Prologue",
        body: "The verb shifts from **ἦν** (“was,” of the Word) to **γίνομαι**, “come into being.” Everything in the created order *becomes*; the Word simply *is*. The aorist **ἐγένετο** views creation as a completed event; the perfect **γέγονεν** (“has come to be”) views the creation as a standing result. Rendering both with the periphrastic **“came to be” / “has come to be”** keeps the single Greek verb visible in English, where “made” would blur it into v. 14’s different vocabulary.",
      },
      {
        kind: "concept", refs: "g1.3.2 g1.3.3", lemma: "δι’ αὐτοῦ",
        title: "Agency: creation “through” him",
        body: "**διά** + genitive marks the Word as the *agent through whom* all things came to be — the same role given to Wisdom (Prov 8:30) and echoed elsewhere (1 Cor 8:6; Col 1:16; Heb 1:2). The Word is neither a second Creator alongside God nor a mere creature: creation happens *through* him. The preposition does real theological work, which is why we resist smoothing it to “by.”",
      },
      {
        kind: "text", refs: "g1.3.11 g1.3.12", lemma: "ὃ γέγονεν",
        title: "A famous punctuation crux",
        body: "The earliest manuscripts had *no punctuation*, so the phrase **ὃ γέγονεν** (“that which has come to be”) can be read two ways. **(a)** With v. 3: “…not one thing came to be that has come to be.” **(b)** With v. 4: “…not one thing came to be. That which has come to be — in him was life.” Reading (b) is ancient and was favored by many Church Fathers; it makes v. 4 begin with a resounding relative clause. Modern editions are divided (NA28 prints it with v. 3; the punctuation was hotly debated in the Arian controversy, since reading (b) could be pressed to make the Spirit or the Word a created “thing”). We print reading (a) but flag (b) as fully live — see the note on v. 4.",
      },
      {
        kind: "p66", refs: "g1.3.4 g1.3.11 g1.3.12", lemma: "ἐγένετο · ὃ γέγονεν",
        title: "𝔓⁶⁶ and the punctuation — a near miss",
        body: "Tantalizingly, 𝔓⁶⁶ *does* punctuate this stretch — but not where it would settle the question. The scribe places a middle dot **after** the first clause (“πάντα δι’ αὐτοῦ ἐγένετο **·**”), yet leaves **no mark at all** at the disputed seam around **ὃ γέγονεν**. So our oldest substantial witness to John shows the same silence as 𝔓⁷⁵*, א*, A, B and D: it does not tell us whether “that which has come to be” closes v. 3 or opens v. 4. The papyrus also reads the imperfect **ἦν** (“was”) in the next line, siding with the standard text against the variant present-tense **ἐστίν** found in some early manuscripts.",
      },
    ],
  },
  4: {
    english: [
      ["In", "g1.4.1"],
      ["him", "g1.4.2"],
      ["was", "g1.4.4"],
      ["life,", "g1.4.3"],
      ["and", "g1.4.5"],
      ["the", "g1.4.6"],
      ["life", "g1.4.7"],
      ["was", "g1.4.8"],
      ["the", "g1.4.9"],
      ["light", "g1.4.10"],
      ["of", "g1.4.11"],
      ["humankind.", "g1.4.11 g1.4.12"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.4.3 g1.4.7", lemma: "ζωή (zōē)",
        title: "“Life” — the Johannine keyword",
        body: "**ζωή** is not biological existence (*bios*) but *life* in the fullest, God-derived sense — what John will call **ζωὴ αἰώνιος**, “eternal life,” the gift the whole Gospel exists to offer (20:31). It is present here “in him” at creation before it becomes the Gospel’s great theme. English has only one word “life,” so the distinction is carried in this note.",
      },
      {
        kind: "concept", refs: "g1.4.10", lemma: "φῶς (phōs)",
        title: "Light — and the dualism it opens",
        body: "With **φῶς** John introduces the light/darkness polarity that runs through the Gospel (3:19–21; 8:12; 12:35–36). It is moral and revelatory, not merely physical: light is life-giving disclosure, the presence that makes seeing — and being seen — possible. The imagery draws on Genesis 1 (“let there be light”) and Isaiah’s servant as “a light to the nations.”",
      },
      {
        kind: "translation", refs: "g1.4.11 g1.4.12", lemma: "τῶν ἀνθρώπων",
        title: "“of humankind,” not “of men”",
        body: "**ἄνθρωπος** denotes a *human being* (as against **ἀνήρ**, an adult male). The older “the light of men” used “men” generically, but modern English hears it as male-specific. We render **“the light of humankind”** to keep the universal scope — the light is for *all people* — while staying literal about the noun.",
      },
      {
        kind: "text", refs: "g1.4.1 g1.4.2 g1.4.3", lemma: "ὃ γέγονεν ἐν αὐτῷ",
        title: "The alternate reading, spelled out",
        body: "If **ὃ γέγονεν** is taken with this verse (see the note on v. 3), the lines read: *“…not one thing came to be. That which has come to be **in him** was life, and the life was the light of humankind.”* The sense becomes: all created things have their true life *in him*. It is grammatically clean and patristically well-attested; we relegate it to the apparatus only because the majority of modern editors join **ὃ γέγονεν** to v. 3.",
      },
    ],
  },
  5: {
    english: [
      ["And", "g1.5.1"],
      ["the", "g1.5.2"],
      ["light", "g1.5.3"],
      ["shines", "g1.5.7"],
      ["in", "g1.5.4"],
      ["the", "g1.5.5"],
      ["darkness,", "g1.5.6"],
      ["and", "g1.5.8"],
      ["the", "g1.5.9"],
      ["darkness", "g1.5.10"],
      ["did", "g1.5.12"],
      ["not", "g1.5.12"],
      ["overcome", "g1.5.13"],
      ["it.", "g1.5.11"],
    ],
    annotations: [
      {
        kind: "grammar", refs: "g1.5.7", lemma: "φαίνει (present tense)",
        title: "The one present-tense verb: “shines”",
        body: "Amid a string of past-tense verbs, **φαίνει** is *present*: the light **shines** — now, continuously. The Prologue’s narrative of primordial creation breaks, for one word, into the reader’s own present. The light did not merely shine; it goes on shining. We keep the present tense in English rather than harmonizing it to “shone.”",
      },
      {
        kind: "translation", refs: "g1.5.13", lemma: "κατέλαβεν (καταλαμβάνω)",
        title: "The deliberate double meaning of “overcome / grasp”",
        body: "**καταλαμβάνω** means to *seize* — and seizing runs in two directions. Hostilely, it is to *overpower, overcome* (so most modern versions: the darkness did not **overcome** it). Cognitively, it is to *grasp, comprehend* (so the KJV: the darkness “**comprehended** it not”). John, a master of double meaning, almost certainly intends both: the darkness neither *extinguished* the light nor *understood* it. English cannot hold both at once; we print **“overcome”** and record the second sense here — arguably the richer half.",
      },
      {
        kind: "concept", refs: "g1.5.6 g1.5.10", lemma: "σκοτία (darkness)",
        title: "Darkness as an actor",
        body: "Note that **σκοτία** is not mere absence but an agent: it is the grammatical subject that fails to “seize” the light. Throughout John, darkness is the sphere and power of unbelief and hostility (cf. 3:19). The verse states the Gospel in miniature: the light meets real resistance, and is not defeated.",
      },
    ],
  },
  6: {
    english: [
      ["There", "", true],
      ["came", "g1.6.1"],
      ["a", "g1.6.2", true],
      ["man,", "g1.6.2"],
      ["sent", "g1.6.3"],
      ["from", "g1.6.4"],
      ["God,", "g1.6.5"],
      ["whose", "g1.6.7"],
      ["name", "g1.6.6"],
      ["was", "", true],
      ["John.", "g1.6.8"],
    ],
    annotations: [
      {
        kind: "grammar", refs: "g1.6.1", lemma: "ἐγένετο (γίνομαι)",
        title: "A pointed change of verb",
        body: "The Prologue has said four times that the Word **ἦν** — “was,” timelessly. Now, of John, it says **ἐγένετο**: he “came to be.” The same verb that governs all created things (v. 3) governs the Baptist. With one word the text files John on the creature’s side of the line it drew in vv. 1–3: the witness *begins*; the Word simply *is*.",
      },
    ],
  },
  7: {
    english: [
      ["This", "g1.7.1"],
      ["man", "g1.7.1"],
      ["came", "g1.7.2"],
      ["as", "g1.7.3"],
      ["a", "g1.7.4", true],
      ["witness,", "g1.7.4"],
      ["to", "g1.7.5"],
      ["testify", "g1.7.6"],
      ["concerning", "g1.7.7"],
      ["the", "g1.7.8"],
      ["light,", "g1.7.9"],
      ["so", "g1.7.10"],
      ["that", "g1.7.10"],
      ["through", "g1.7.13"],
      ["him", "g1.7.14"],
      ["all", "g1.7.11"],
      ["might", "g1.7.12"],
      ["believe.", "g1.7.12"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.7.4 g1.7.6", lemma: "μαρτυρία / μαρτυρέω",
        title: "Witness — the Gospel’s courtroom",
        body: "The **witness** word-group (*martyria*, *martyreō*) is one of John’s master-images: the whole Gospel is staged as a kind of trial in which testimony is given for and against Jesus. John the Baptist is the first witness called. Note how narrowly his role is drawn — he comes *for* witness, *to* witness, so that *others* might believe. He is a voice pointing away from himself.",
      },
    ],
  },
  8: {
    english: [
      ["He", "g1.8.3"],
      ["was", "g1.8.2"],
      ["not", "g1.8.1"],
      ["the", "g1.8.4"],
      ["light,", "g1.8.5"],
      ["but", "g1.8.6"],
      ["came", "", true],
      ["to", "g1.8.7"],
      ["testify", "g1.8.8"],
      ["concerning", "g1.8.9"],
      ["the", "g1.8.10"],
      ["light.", "g1.8.11"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.8.3 g1.8.1", lemma: "οὐκ ἦν ἐκεῖνος",
        title: "An emphatic denial: “*he* was not the light”",
        body: "The pronoun **ἐκεῖνος** (“that one, he”) is emphatic and the negative **οὐκ** stands first: *not the light was he*. Many scholars hear a polemical edge — there were those (a Baptist movement is attested even into the second century) who ranked John too highly. The Prologue is careful: John is the lamp, not the light; the reflector, not the source.",
      },
    ],
  },
  9: {
    english: [
      ["The", "g1.9.2"],
      ["true", "g1.9.5"],
      ["light,", "g1.9.3"],
      ["which", "g1.9.6"],
      ["gives", "g1.9.7"],
      ["light", "g1.9.7"],
      ["to", "", true],
      ["every", "g1.9.8"],
      ["person,", "g1.9.9"],
      ["was", "g1.9.1"],
      ["coming", "g1.9.10"],
      ["into", "g1.9.11"],
      ["the", "g1.9.12"],
      ["world.", "g1.9.13"],
    ],
    annotations: [
      {
        kind: "grammar", refs: "g1.9.1 g1.9.10", lemma: "Ἦν … ἐρχόμενον",
        title: "What is “coming into the world”?",
        body: "The participle **ἐρχόμενον** (“coming”) is grammatically ambiguous. It can attach to **ἄνθρωπον**: “every person *coming into the world*” — a known Hebrew idiom simply meaning “everyone born.” Or it can complete the periphrastic imperfect **ἦν … ἐρχόμενον**: “the true light … *was coming* into the world.” We take the second (with most modern versions): the verse announces the light’s advent, preparing for v. 14. The note preserves the first reading, which is ancient and grammatically clean.",
      },
      {
        kind: "concept", refs: "g1.9.5 g1.9.7", lemma: "ἀληθινόν · φωτίζει",
        title: "“True” light that enlightens everyone",
        body: "**ἀληθινός** is “true” in the sense of *real, archetypal* — the genuine article of which other lights are shadows. That this light **φωτίζει πάντα ἄνθρωπον** (“gives light to every person”) has been read two ways: as a universal inward illumination (a light in every conscience), or as the light now *shining upon* all without exception in the incarnate Word. John leaves the scope deliberately wide.",
      },
    ],
  },
  10: {
    english: [
      ["He", "", true],
      ["was", "g1.10.4"],
      ["in", "g1.10.1"],
      ["the", "g1.10.2"],
      ["world,", "g1.10.3"],
      ["and", "g1.10.5"],
      ["the", "g1.10.6"],
      ["world", "g1.10.7"],
      ["came", "g1.10.10"],
      ["to", "g1.10.10"],
      ["be", "g1.10.10"],
      ["through", "g1.10.8"],
      ["him,", "g1.10.9"],
      ["and", "g1.10.11"],
      ["the", "g1.10.12"],
      ["world", "g1.10.13"],
      ["did", "g1.10.15"],
      ["not", "g1.10.15"],
      ["know", "g1.10.16"],
      ["him.", "g1.10.14"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.10.3 g1.10.7 g1.10.13", lemma: "κόσμος (kosmos)",
        title: "Three senses of “world” in one breath",
        body: "John rings the changes on **κόσμος** in a single verse. “He was *in the world*” — the created arena. “The world *came to be through him*” — the sum of created things. “The world *did not know him*” — humanity organized in estrangement from God. This last, moral sense becomes dominant later (the “world” that hates the light). The tragedy is compressed grammatically: the world owes him its very existence, and does not recognize him.",
      },
      {
        kind: "concept", refs: "g1.10.16", lemma: "ἔγνω (γινώσκω)",
        title: "“Did not know” — a failure of recognition",
        body: "**γινώσκω** is *relational* knowing — recognition, acknowledgement — not mere information. The world’s failure is not ignorance of a fact but refusal of a person. The same verb will describe the intimacy Jesus offers his own (10:14).",
      },
    ],
  },
  11: {
    english: [
      ["He", "", true],
      ["came", "g1.11.4"],
      ["to", "g1.11.1"],
      ["his", "g1.11.3"],
      ["own,", "g1.11.3"],
      ["and", "g1.11.5"],
      ["his", "g1.11.7"],
      ["own", "g1.11.7"],
      ["people", "g1.11.6"],
      ["did", "g1.11.9"],
      ["not", "g1.11.9"],
      ["receive", "g1.11.10"],
      ["him.", "g1.11.8"],
    ],
    annotations: [
      {
        kind: "translation", refs: "g1.11.3 g1.11.7", lemma: "τὰ ἴδια · οἱ ἴδιοι",
        title: "A wordplay lost in English: his own *place*, his own *people*",
        body: "The same root **ἴδιος** (“one’s own”) appears twice, in two genders. First neuter plural **τὰ ἴδια** — “his own *things / home / domain*.” Then masculine plural **οἱ ἴδιοι** — “his own *people*.” He came to his own *home*, and his own *family* would not take him in. English cannot voice both with one word, so we render “his own … his own people” and mark the play here. The primary reference is almost certainly to Israel, and behind it, the whole creation.",
      },
    ],
  },
  12: {
    english: [
      ["But", "g1.12.2"],
      ["to", "g1.12.1"],
      ["all", "g1.12.1"],
      ["who", "g1.12.1"],
      ["received", "g1.12.3"],
      ["him,", "g1.12.4"],
      ["he", "g1.12.5"],
      ["gave", "g1.12.5"],
      ["them", "g1.12.6"],
      ["the", "g1.12.7"],
      ["right", "g1.12.7"],
      ["to", "g1.12.10"],
      ["become", "g1.12.10"],
      ["children", "g1.12.8"],
      ["of", "g1.12.9"],
      ["God", "g1.12.9"],
      ["—", "", true],
      ["to", "g1.12.11"],
      ["those", "g1.12.11"],
      ["who", "g1.12.12"],
      ["believe", "g1.12.12"],
      ["in", "g1.12.13"],
      ["his", "g1.12.16"],
      ["name.", "g1.12.15"],
    ],
    annotations: [
      {
        kind: "translation", refs: "g1.12.7", lemma: "ἐξουσία",
        title: "“Right,” not “power”",
        body: "**ἐξουσία** is *authorization* — the granted right or freedom to do something — not raw **δύναμις** (“power”). Becoming a child of God is not a human achievement seized by force; it is a *right conferred*. The KJV’s “power” misleads a modern ear; “right” or “authority” is closer.",
      },
      {
        kind: "concept", refs: "g1.12.8 g1.12.12", lemma: "τέκνα θεοῦ · πιστεύω εἰς",
        title: "Children of God — and “believing into” a name",
        body: "John reserves **υἱός** (“Son”) for Christ and calls believers **τέκνα** (“children”) — a deliberate distinction of kind: he is Son by nature, they by gift. And the phrase is **πιστεύω εἰς** — literally to “believe *into*” his name, John’s signature construction. It is not assent to a proposition but self-committing trust *directed toward* a person, moving the believer *into* him.",
      },
    ],
  },
  13: {
    english: [
      ["who", "g1.13.1"],
      ["were", "g1.13.16"],
      ["born,", "g1.13.16"],
      ["not", "g1.13.2"],
      ["of", "g1.13.3"],
      ["blood,", "g1.13.4"],
      ["nor", "g1.13.5"],
      ["of", "g1.13.6"],
      ["the", "g1.13.7", true],
      ["will", "g1.13.7"],
      ["of", "g1.13.8"],
      ["the", "g1.13.8", true],
      ["flesh,", "g1.13.8"],
      ["nor", "g1.13.9"],
      ["of", "g1.13.10"],
      ["the", "g1.13.11", true],
      ["will", "g1.13.11"],
      ["of", "g1.13.12"],
      ["a", "g1.13.12", true],
      ["man,", "g1.13.12"],
      ["but", "g1.13.13"],
      ["of", "g1.13.14"],
      ["God.", "g1.13.15"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.13.4 g1.13.16", lemma: "ἐξ αἱμάτων … ἐγεννήθησαν",
        title: "A birth “not of bloods”",
        body: "The Greek **αἱμάτων** is *plural* — “bloods” — reflecting an ancient notion of conception as a mingling of bloods. Three natural sources of life are denied in turn: bloods, the will of the flesh, the will of a man. Over against every human generation stands the one true origin: **ἐκ Θεοῦ ἐγεννήθησαν**, “they were begotten of God.” The children of v. 12 are made, not born in the ordinary way.",
      },
      {
        kind: "text", refs: "g1.13.1 g1.13.16", lemma: "οἳ … ἐγεννήθησαν",
        title: "A singular reading with a long history",
        body: "A handful of witnesses (chiefly Old Latin, and some patristic citations) read the whole verse in the *singular* — “**who was** born, not of bloods … but of God” — making it a statement about the virgin birth of Christ rather than the new birth of believers. The Greek manuscript tradition overwhelmingly supports the *plural* (“who **were** born”), which we print; but the singular was known early and prized by some Fathers, and it shows how a single ending can shift a verse from soteriology to Christology.",
      },
    ],
  },
  14: {
    english: [
      ["And", "g1.14.1"],
      ["the", "g1.14.2"],
      ["Word", "g1.14.3"],
      ["became", "g1.14.5"],
      ["flesh", "g1.14.4"],
      ["and", "g1.14.6"],
      ["pitched", "g1.14.7"],
      ["his", "g1.14.7", true],
      ["tent", "g1.14.7"],
      ["among", "g1.14.8"],
      ["us,", "g1.14.9"],
      ["and", "g1.14.10"],
      ["we", "g1.14.11"],
      ["beheld", "g1.14.11"],
      ["his", "g1.14.14"],
      ["glory,", "g1.14.13"],
      ["glory", "g1.14.15"],
      ["as", "g1.14.16"],
      ["of", "g1.14.17", true],
      ["the", "g1.14.17", true],
      ["only", "g1.14.17"],
      ["Son", "g1.14.17", true],
      ["from", "g1.14.18"],
      ["the", "g1.14.19", true],
      ["Father,", "g1.14.19"],
      ["full", "g1.14.20"],
      ["of", "", true],
      ["grace", "g1.14.21"],
      ["and", "g1.14.22"],
      ["truth.", "g1.14.23"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.14.3 g1.14.5 g1.14.4", lemma: "ὁ Λόγος σὰρξ ἐγένετο",
        title: "The turn of the whole Gospel: “the Word became flesh”",
        body: "The verb is **ἐγένετο** once more — the Word who *was* (ἦν) now *became*. And what he became is **σάρξ**, “flesh” — not merely “a body” or “a man” but frail, mortal humanity in its weakness. John does not say the Word *entered* flesh or *seemed* flesh; he *became* it. Against every docetism, the shock is intended.",
      },
      {
        kind: "concept", refs: "g1.14.7 g1.14.13", lemma: "ἐσκήνωσεν · δόξα",
        title: "“Pitched his tent” — the Tabernacle and the Glory",
        body: "**σκηνόω** means to *pitch a tent, encamp*; we render it woodenly to keep the image. It evokes the **σκηνή**, the wilderness Tabernacle where God’s glory (the *Shekinah*) dwelt among Israel — the consonants of the Hebrew *shakan* even echo in the Greek. So when the next clause says “we **beheld his glory** (**δόξα**),” the claim is staggering: the Sinai glory that filled the tent now tents in a human life, and was *seen*.",
      },
      {
        kind: "translation", refs: "g1.14.17", lemma: "μονογενής",
        title: "“Only-begotten” or “only / one-of-a-kind”?",
        body: "**μονογενής** is *monos* (“only”) + *genos* (“kind, class”), i.e. *unique, one of a kind* — not *monos* + *gennaō* (“beget”). The traditional “only-begotten” comes through the Latin *unigenitus* and reads a later doctrine of eternal generation back into the word. The plain sense is “the *only* Son,” the *one and only*. We supply “Son” (the Greek has only the adjective) because the family imagery of *Father* requires it.",
      },
      {
        kind: "concept", refs: "g1.14.21 g1.14.23", lemma: "χάριτος καὶ ἀληθείας",
        title: "“Grace and truth” — a Hebrew pair",
        body: "**χάρις καὶ ἀλήθεια** almost certainly renders the great covenant pair **חֶסֶד וֶאֱמֶת** (*ḥesed we-ʾemet*), “steadfast love and faithfulness” — the very words God speaks of himself to Moses at Sinai (Exod 34:6). The incarnate Word is “full” of exactly what YHWH declared himself to be. This quietly sets up v. 17.",
      },
    ],
  },
  15: {
    english: [
      ["John", "g1.15.1"],
      ["bears", "g1.15.2"],
      ["witness", "g1.15.2"],
      ["about", "g1.15.3"],
      ["him", "g1.15.4"],
      ["and", "g1.15.5"],
      ["has", "g1.15.6"],
      ["cried", "g1.15.6"],
      ["out,", "g1.15.6"],
      ["saying:", "g1.15.7"],
      ["This", "g1.15.8"],
      ["was", "g1.15.9"],
      ["he", "", true],
      ["of", "g1.15.10"],
      ["whom", "g1.15.10"],
      ["I", "g1.15.11"],
      ["said,", "g1.15.11"],
      ["the", "g1.15.12"],
      ["one", "g1.15.12"],
      ["coming", "g1.15.15"],
      ["after", "g1.15.13"],
      ["me", "g1.15.14"],
      ["has", "g1.15.18"],
      ["come", "g1.15.18"],
      ["to", "g1.15.18"],
      ["be", "g1.15.18"],
      ["ahead", "g1.15.16"],
      ["of", "g1.15.16"],
      ["me,", "g1.15.17"],
      ["because", "g1.15.19"],
      ["he", "", true],
      ["was", "g1.15.22"],
      ["before", "g1.15.20"],
      ["me.", "g1.15.21"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.15.13 g1.15.16 g1.15.20 g1.15.22", lemma: "ὀπίσω … ἔμπροσθεν … πρῶτος",
        title: "A riddle of before-and-after",
        body: "The Baptist’s saying turns on three position-words. The one who comes **ὀπίσω** (“after”) John in time has come to be **ἔμπροσθεν** (“ahead / before”) him in rank — “because he **was** (**ἦν**) **πρῶτός** (first / prior to) me.” The final **ἦν** is the Prologue’s timeless “was” again: Jesus outranks his forerunner because he *pre-existed* him. Chronology is overturned by eternity.",
      },
    ],
  },
  16: {
    english: [
      ["For", "g1.16.1"],
      ["from", "g1.16.2"],
      ["his", "g1.16.5"],
      ["fullness", "g1.16.4"],
      ["we", "g1.16.6"],
      ["have", "g1.16.8"],
      ["all", "g1.16.7"],
      ["received,", "g1.16.8"],
      ["and", "g1.16.9"],
      ["grace", "g1.16.10"],
      ["upon", "g1.16.11"],
      ["grace.", "g1.16.12"],
    ],
    annotations: [
      {
        kind: "translation", refs: "g1.16.10 g1.16.11 g1.16.12", lemma: "χάριν ἀντὶ χάριτος",
        title: "“Grace upon grace” — or grace *replacing* grace?",
        body: "The preposition **ἀντί** normally means “instead of, in place of.” So the phrase can mean grace *heaped upon* grace (wave after wave), or grace *in exchange for* grace — the grace of the new covenant replacing the earlier grace of the law. Read with v. 17 following, the “replacement / fulfilment” sense is attractive: gift succeeding gift. We keep the familiar “grace upon grace” and note the alternative.",
      },
    ],
  },
  17: {
    english: [
      ["For", "g1.17.1"],
      ["the", "g1.17.2"],
      ["law", "g1.17.3"],
      ["was", "g1.17.6"],
      ["given", "g1.17.6"],
      ["through", "g1.17.4"],
      ["Moses;", "g1.17.5"],
      ["grace", "g1.17.8"],
      ["and", "g1.17.9"],
      ["truth", "g1.17.11"],
      ["came", "g1.17.15"],
      ["through", "g1.17.12"],
      ["Jesus", "g1.17.13"],
      ["Christ.", "g1.17.14"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.17.3 g1.17.13 g1.17.15", lemma: "νόμος … Ἰησοῦ Χριστοῦ",
        title: "Moses and the Messiah — contrast, not rejection",
        body: "The parallel is sharp but not simply hostile: the law “**was given**” (a completed gift) through Moses; “grace and truth” **ἐγένετο** — *came to be* — through Jesus Christ. Note the verb is **γίνομαι** yet again, binding this to the Word through whom all things came to be. This is also the first time the Gospel speaks the full name **Ἰησοῦς Χριστός**: only now, at the Prologue’s end, is the Word given his human name.",
      },
    ],
  },
  18: {
    english: [
      ["No", "g1.18.2"],
      ["one", "g1.18.2"],
      ["has", "g1.18.3"],
      ["ever", "g1.18.4"],
      ["seen", "g1.18.3"],
      ["God;", "g1.18.1"],
      ["the", "g1.18.5", true],
      ["only", "g1.18.5"],
      ["God,", "g1.18.6"],
      ["who", "g1.18.7"],
      ["is", "g1.18.8"],
      ["at", "g1.18.9"],
      ["the", "g1.18.12"],
      ["Father’s", "g1.18.13"],
      ["side,", "g1.18.11"],
      ["he", "g1.18.14"],
      ["has", "g1.18.15"],
      ["made", "g1.18.15"],
      ["him", "g1.18.15", true],
      ["known.", "g1.18.15"],
    ],
    annotations: [
      {
        kind: "text", refs: "g1.18.5 g1.18.6", lemma: "μονογενὴς θεός / υἱός",
        title: "The hardest variant in the Prologue",
        body: "Did John write **μονογενὴς θεός** (“the only *God*,” or “God the only Son”) or **μονογενὴς υἱός** (“the only *Son*”)? The reading “**God**” is the harder and earlier one, and we print it (with Nestle 1904). It makes the verse frame the whole Prologue: it opened with “the Word was God” (v. 1) and now closes with “the only God … has made him known.” See the 𝔓⁶⁶ note.",
      },
      {
        kind: "p66", refs: "g1.18.5 g1.18.6", lemma: "μονογενὴς θεός",
        title: "𝔓⁶⁶ backs the harder reading",
        body: "This is where 𝔓⁶⁶ speaks clearly and early. Together with 𝔓⁷⁵ and the great codices א and B, it reads **μονογενὴς θεός** — “only God” — not the smoother **υἱός** (“Son”) of the later majority. Two of our oldest witnesses to John, from around the turn of the third century, thus support the reading that most startles: the *only-begotten God*. (Here, unlike v. 1, the θεός is on the page, not reconstructed.)",
      },
      {
        kind: "translation", refs: "g1.18.15 g1.18.11", lemma: "ἐξηγήσατο · κόλπος",
        title: "He “exegeted” the Father",
        body: "The last verb is **ἐξηγέομαι** — to *lead out, narrate, expound*; our word **exegesis** comes straight from it. The unseen God is not merely reported but *interpreted, made known* by the one who is **εἰς τὸν κόλπον** — “at the *bosom* / side” of the Father, the place of closest intimacy (cf. 13:23). The Prologue ends where it began: the Word is God’s self-explanation.",
      },
    ],
  },
  19: {
    english: [
      ["And", "g1.19.1"],
      ["this", "g1.19.2"],
      ["is", "g1.19.3"],
      ["the", "g1.19.4"],
      ["testimony", "g1.19.5"],
      ["of", "g1.19.6"],
      ["John,", "g1.19.7"],
      ["when", "g1.19.8"],
      ["the", "g1.19.12"],
      ["Jews", "g1.19.13"],
      ["sent", "g1.19.9"],
      ["priests", "g1.19.16"],
      ["and", "g1.19.17"],
      ["Levites", "g1.19.18"],
      ["to", "g1.19.10"],
      ["him", "g1.19.11"],
      ["from", "g1.19.14"],
      ["Jerusalem", "g1.19.15"],
      ["to", "g1.19.19"],
      ["ask", "g1.19.20"],
      ["him,", "g1.19.21"],
      ["“Who", "g1.19.23"],
      ["are", "g1.19.24"],
      ["you?”", "g1.19.22"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.19.13 g1.19.16 g1.19.18", lemma: "οἱ Ἰουδαῖοι",
        title: "“The Jews” — usually the authorities",
        body: "In John, **οἱ Ἰουδαῖοι** (“the Jews”) rarely means the people at large; it most often denotes the *Judean religious establishment* centred on Jerusalem — here specified as **priests and Levites**. It is an in-house dispute: Jesus, his first followers, and John the Baptist are all Jews. Rendering it flatly “the Jews” has done real historical harm; the sense is closer to “the Judean authorities.”",
      },
    ],
  },
  20: {
    english: [
      ["And", "g1.20.1"],
      ["he", "", true],
      ["confessed", "g1.20.2"],
      ["and", "g1.20.3"],
      ["did", "g1.20.4"],
      ["not", "g1.20.4"],
      ["deny,", "g1.20.5"],
      ["but", "g1.20.6"],
      ["confessed:", "g1.20.7"],
      ["“I", "g1.20.9"],
      ["am", "g1.20.11"],
      ["not", "g1.20.10"],
      ["the", "g1.20.12"],
      ["Christ.”", "g1.20.13"],
    ],
    annotations: [
      {
        kind: "grammar", refs: "g1.20.2 g1.20.5 g1.20.7", lemma: "ὡμολόγησεν … οὐκ ἠρνήσατο",
        title: "A solemn, threefold disclaimer",
        body: "The line is almost liturgical in its emphasis: “he **confessed** and did **not deny**, but **confessed**.” The doubling of the positive around a negative hammers the point home. Whatever popular enthusiasm surrounded the Baptist, John flatly forecloses it: **ἐγὼ οὐκ εἰμὶ ὁ Χριστός**, “I am not the Christ.” The emphatic **ἐγώ** (“*I*”) quietly leaves room for the one who can say “I am.”",
      },
    ],
  },
  21: {
    english: [
      ["And", "g1.21.1"],
      ["they", "", true],
      ["asked", "g1.21.2"],
      ["him,", "g1.21.3"],
      ["“What", "g1.21.4"],
      ["then?”", "g1.21.5"],
      ["“Are", "g1.21.8"],
      ["you", "g1.21.6"],
      ["Elijah?”", "g1.21.7"],
      ["And", "g1.21.9"],
      ["he", "", true],
      ["says,", "g1.21.10"],
      ["“I", "", true],
      ["am", "g1.21.12"],
      ["not.”", "g1.21.11"],
      ["“Are", "g1.21.15"],
      ["you", "g1.21.16"],
      ["the", "g1.21.13"],
      ["Prophet?”", "g1.21.14"],
      ["And", "g1.21.17"],
      ["he", "", true],
      ["answered,", "g1.21.18"],
      ["“No.”", "g1.21.19"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.21.7 g1.21.14", lemma: "Ἡλείας · ὁ προφήτης",
        title: "Elijah and “the Prophet”",
        body: "Two live expectations. **Elijah** was to return before the Day of the LORD (Mal 4:5) — and, strikingly, John denies being him, though Jesus elsewhere says John *is* Elijah “in spirit” (Matt 11:14). **The Prophet** is the one “like Moses” promised in Deut 18:15. John waves away all three titles — Christ, Elijah, the Prophet — refusing every category that would centre attention on himself.",
      },
    ],
  },
  22: {
    english: [
      ["So", "g1.22.2"],
      ["they", "g1.22.1"],
      ["said", "g1.22.1"],
      ["to", "g1.22.3"],
      ["him,", "g1.22.3"],
      ["“Who", "g1.22.4"],
      ["are", "g1.22.5"],
      ["you?", "g1.22.5"],
      ["so", "g1.22.6"],
      ["that", "g1.22.6"],
      ["we", "g1.22.8"],
      ["may", "g1.22.8"],
      ["give", "g1.22.8"],
      ["an", "g1.22.7"],
      ["answer", "g1.22.7"],
      ["to", "g1.22.9"],
      ["those", "g1.22.9"],
      ["who", "g1.22.10"],
      ["sent", "g1.22.10"],
      ["us.", "g1.22.11"],
      ["What", "g1.22.12"],
      ["do", "g1.22.13"],
      ["you", "g1.22.13"],
      ["say", "g1.22.13"],
      ["about", "g1.22.14"],
      ["yourself?”", "g1.22.15"],
    ],
    annotations: [
    ],
  },
  23: {
    english: [
      ["He", "", true],
      ["said,", "g1.23.1"],
      ["“I", "g1.23.2"],
      ["am", "", true],
      ["a", "g1.23.3", true],
      ["voice", "g1.23.3"],
      ["of", "g1.23.4"],
      ["one", "g1.23.4"],
      ["crying", "g1.23.4"],
      ["in", "g1.23.5"],
      ["the", "g1.23.6"],
      ["wilderness:", "g1.23.7"],
      ["Make", "g1.23.8"],
      ["straight", "g1.23.8"],
      ["the", "g1.23.9"],
      ["way", "g1.23.10"],
      ["of", "g1.23.11"],
      ["the", "g1.23.11"],
      ["Lord,”", "g1.23.11"],
      ["as", "g1.23.12"],
      ["Isaiah", "g1.23.14"],
      ["the", "g1.23.15"],
      ["prophet", "g1.23.16"],
      ["said.", "g1.23.13"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.23.3 g1.23.7", lemma: "φωνὴ βοῶντος",
        title: "Only a voice",
        body: "Asked *who* he is, John answers with a *what*: he is a **voice** (Isa 40:3). The Synoptics apply that verse *to* John; here John applies it *to himself*, and it is the sole identity he claims. A voice exists only for the word it carries and then fades — the perfect self-description for the forerunner. Note he says nothing of Elijah or the Prophet; he is pure pointer.",
      },
    ],
  },
  24: {
    english: [
      ["Now", "g1.24.1"],
      ["they", "", true],
      ["had", "g1.24.3"],
      ["been", "g1.24.3"],
      ["sent", "g1.24.2"],
      ["from", "g1.24.4"],
      ["the", "g1.24.5"],
      ["Pharisees.", "g1.24.6"],
    ],
    annotations: [
    ],
  },
  25: {
    english: [
      ["And", "g1.25.1"],
      ["they", "", true],
      ["asked", "g1.25.2"],
      ["him", "g1.25.3"],
      ["and", "g1.25.4"],
      ["said", "g1.25.5"],
      ["to", "g1.25.6"],
      ["him,", "g1.25.6"],
      ["“Why", "g1.25.7"],
      ["then", "g1.25.8"],
      ["do", "g1.25.9"],
      ["you", "g1.25.9"],
      ["baptize,", "g1.25.9"],
      ["if", "g1.25.10"],
      ["you", "g1.25.11"],
      ["are", "g1.25.13"],
      ["not", "g1.25.12"],
      ["the", "g1.25.14"],
      ["Christ,", "g1.25.15"],
      ["nor", "g1.25.16"],
      ["Elijah,", "g1.25.17"],
      ["nor", "g1.25.18"],
      ["the", "g1.25.19"],
      ["Prophet?”", "g1.25.20"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.25.9", lemma: "τί βαπτίζεις;",
        title: "Why baptize at all?",
        body: "The question assumes that a ritual washing of *all Israel* belonged to the last days — the eschatological cleansing promised in Ezekiel 36:25 and Zechariah 13:1, or the immersion expected of the Messiah, Elijah, or the Prophet. If John claims none of those roles, by whose authority does he baptize? The stage is set for his answer: his water points beyond itself.",
      },
    ],
  },
  26: {
    english: [
      ["John", "g1.26.4"],
      ["answered", "g1.26.1"],
      ["them,", "g1.26.2"],
      ["saying,", "g1.26.5"],
      ["“I", "g1.26.6"],
      ["baptize", "g1.26.7"],
      ["with", "g1.26.8"],
      ["water.", "g1.26.9"],
      ["Among", "g1.26.10"],
      ["you", "g1.26.11"],
      ["stands", "g1.26.12"],
      ["one", "", true],
      ["whom", "g1.26.13"],
      ["you", "g1.26.14"],
      ["do", "g1.26.15"],
      ["not", "g1.26.15"],
      ["know,", "g1.26.16"],
    ],
    annotations: [
    ],
  },
  27: {
    english: [
      ["the", "g1.27.1"],
      ["one", "g1.27.4"],
      ["coming", "g1.27.4"],
      ["after", "g1.27.2"],
      ["me,", "g1.27.3"],
      ["the", "g1.27.13"],
      ["strap", "g1.27.14"],
      ["of", "g1.27.5"],
      ["whose", "g1.27.5"],
      ["sandal", "g1.27.16"],
      ["I", "g1.27.8"],
      ["am", "g1.27.7"],
      ["not", "g1.27.6"],
      ["worthy", "g1.27.9"],
      ["to", "g1.27.10"],
      ["untie.", "g1.27.11"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.27.14 g1.27.11", lemma: "λύσω … τὸν ἱμάντα",
        title: "Lower than a slave",
        body: "Untying a master’s sandal-strap was slave’s work — so menial that a rabbinic saying held a disciple should do for his teacher anything a slave does *except* loosen his sandals. John says he is unworthy even of that. The forerunner measures the immeasurable distance between himself and the one who comes after.",
      },
    ],
  },
  28: {
    english: [
      ["These", "g1.28.1"],
      ["things", "g1.28.1"],
      ["took", "g1.28.4"],
      ["place", "g1.28.4"],
      ["in", "g1.28.2"],
      ["Bethany", "g1.28.3"],
      ["beyond", "g1.28.5"],
      ["the", "g1.28.6"],
      ["Jordan,", "g1.28.7"],
      ["where", "g1.28.8"],
      ["John", "g1.28.11"],
      ["was", "g1.28.9"],
      ["baptizing.", "g1.28.12"],
    ],
    annotations: [
      {
        kind: "text", refs: "g1.28.3", lemma: "Βηθανίᾳ",
        title: "Bethany — or Bethabara?",
        body: "This is **not** the Bethany near Jerusalem (of Mary, Martha, and Lazarus) but a place *beyond the Jordan*. The manuscripts read **Βηθανίᾳ**, but a notable early tradition — followed by Origen, who searched the region and could find no Bethany there — reads **Βηθαβαρᾷ** (Bethabara). Most editors keep “Bethany” as the harder, better-attested reading and treat the site as otherwise unknown.",
      },
    ],
  },
  29: {
    english: [
      ["The", "g1.29.1"],
      ["next", "g1.29.2"],
      ["day", "g1.29.2"],
      ["he", "", true],
      ["sees", "g1.29.3"],
      ["Jesus", "g1.29.5"],
      ["coming", "g1.29.6"],
      ["toward", "g1.29.7"],
      ["him,", "g1.29.8"],
      ["and", "g1.29.9"],
      ["says,", "g1.29.10"],
      ["“Behold,", "g1.29.11"],
      ["the", "g1.29.12"],
      ["Lamb", "g1.29.13"],
      ["of", "g1.29.15"],
      ["God", "g1.29.15"],
      ["who", "g1.29.16"],
      ["takes", "g1.29.17"],
      ["away", "g1.29.17"],
      ["the", "g1.29.18"],
      ["sin", "g1.29.19"],
      ["of", "g1.29.20"],
      ["the", "g1.29.20"],
      ["world!”", "g1.29.21"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.29.13 g1.29.15", lemma: "ὁ Ἀμνὸς τοῦ Θεοῦ",
        title: "“The Lamb of God” — which lamb?",
        body: "John fuses several lambs into one title. The **Passover lamb**, whose blood shielded Israel (Exod 12) — this Gospel will have Jesus die as the lambs are slain, with no bone broken (19:36). The lamb of **Isaiah 53:7**, “led like a lamb to the slaughter,” bearing the sins of many. The daily **tamid** lamb of the temple. Perhaps the ram of the **Aqedah** (Gen 22), God’s own provision. The one figure gathers up the whole sacrificial hope of Israel.",
      },
      {
        kind: "translation", refs: "g1.29.17 g1.29.19", lemma: "ὁ αἴρων τὴν ἁμαρτίαν",
        title: "“Takes away” — and takes up",
        body: "**αἴρω** means both to *lift up, take upon oneself* and to *carry off, remove*. The Lamb does both: he *bears* sin and *bears it away* (the sacrifice and the scapegoat in one). And **ἁμαρτίαν** is *singular* — not a tally of misdeeds but “the **sin** of the world,” humanity’s estrangement gathered into a single mass and lifted off.",
      },
      {
        kind: "reading", refs: "g1.29.13 g1.29.19",
        title: "“The Lamb of God”: the shape of this rescue",
        body: "Israel waited for many kinds of deliverer — a king like David, a prophet like Moses, a heavenly judge. What almost no one expected was a **lamb**. John the Baptist’s cry names the strange logic of this whole Gospel: the Messiah rescues not by conquering but by being *offered*. The image fuses several sacrifices at once — the **Passover** lamb whose blood shields from death, the silent lamb “led to the slaughter” who bears others’ guilt (Isa 53), the daily temple offering — and points them all forward to the cross. Notice the scope: not the sins of Israel but **“the sin of the world,”** gathered into one mass and carried off. If the sign at Cana hinted that God’s power looks like generous self-giving rather than force, this title says it outright. The Lion of Judah turns out to be a Lamb — and that reversal is close to the centre of what the New Testament means by “glory.”",
      },
    ],
  },
  30: {
    english: [
      ["This", "g1.30.1"],
      ["is", "g1.30.2"],
      ["he", "", true],
      ["of", "g1.30.3"],
      ["whom", "g1.30.4"],
      ["I", "g1.30.5"],
      ["said,", "g1.30.6"],
      ["“After", "g1.30.7"],
      ["me", "g1.30.8"],
      ["comes", "g1.30.9"],
      ["a", "g1.30.10", true],
      ["man", "g1.30.10"],
      ["who", "g1.30.11"],
      ["has", "g1.30.14"],
      ["come", "g1.30.14"],
      ["to", "g1.30.14"],
      ["be", "g1.30.14"],
      ["ahead", "g1.30.12"],
      ["of", "g1.30.12"],
      ["me,", "g1.30.13"],
      ["because", "g1.30.15"],
      ["he", "", true],
      ["was", "g1.30.18"],
      ["before", "g1.30.16"],
      ["me.”", "g1.30.17"],
    ],
    annotations: [
      {
        kind: "grammar", refs: "g1.30.10 g1.30.18", lemma: "ἀνήρ · ἦν",
        title: "The riddle returns",
        body: "John repeats his saying from v. 15 almost word for word, now naming the one who comes as **ἀνήρ**, “a man.” The paradox stands: the later-comer ranks *ahead* because he existed *before* — and the reason is once again the Prologue’s timeless **ἦν**, “he *was*.” The witness has met, in the flesh, the pre-existent Word he announced.",
      },
    ],
  },
  31: {
    english: [
      ["And", "g1.31.1"],
      ["I", "g1.31.1"],
      ["myself", "", true],
      ["did", "g1.31.2"],
      ["not", "g1.31.2"],
      ["know", "g1.31.3"],
      ["him,", "g1.31.4"],
      ["but", "g1.31.5"],
      ["that", "g1.31.6"],
      ["he", "g1.31.7"],
      ["might", "g1.31.7"],
      ["be", "g1.31.7"],
      ["revealed", "g1.31.7"],
      ["to", "g1.31.8"],
      ["Israel,", "g1.31.9"],
      ["for", "g1.31.10"],
      ["this", "g1.31.11"],
      ["I", "g1.31.13"],
      ["came", "g1.31.12"],
      ["baptizing", "g1.31.16"],
      ["with", "g1.31.14"],
      ["water.", "g1.31.15"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.31.3 g1.31.7", lemma: "οὐκ ᾔδειν … φανερωθῇ",
        title: "The point of the water",
        body: "Twice John says “I did not know him” (vv. 31, 33) — no private tip-off, no family arrangement (though Luke makes them kin). His whole baptizing ministry existed for one purpose: **ἵνα φανερωθῇ τῷ Ἰσραήλ**, “that he might be *revealed* to Israel.” The water was never the point; the unveiling was.",
      },
    ],
  },
  32: {
    english: [
      ["And", "g1.32.1"],
      ["John", "g1.32.3"],
      ["bore", "g1.32.2"],
      ["witness,", "g1.32.2"],
      ["saying,", "g1.32.4"],
      ["“I", "g1.32.6"],
      ["have", "g1.32.6"],
      ["beheld", "g1.32.6"],
      ["the", "g1.32.7"],
      ["Spirit", "g1.32.8"],
      ["descending", "g1.32.9"],
      ["like", "g1.32.10"],
      ["a", "g1.32.11", true],
      ["dove", "g1.32.11"],
      ["out", "g1.32.12"],
      ["of", "g1.32.12"],
      ["heaven,", "g1.32.13"],
      ["and", "g1.32.14"],
      ["it", "", true],
      ["remained", "g1.32.15"],
      ["upon", "g1.32.16"],
      ["him.", "g1.32.17"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.32.15 g1.32.11", lemma: "ἔμεινεν · περιστερά",
        title: "The Spirit that *stays*",
        body: "The decisive word is **μένω**, “remain, abide.” The Spirit does not merely alight and depart, as it came upon the old prophets for a season; it **descends and remains**. That permanence is the sign that marks Jesus out. The **dove** carries its own echoes — the Spirit hovering over the waters at creation (Gen 1:2), the dove of Noah signalling a new world, and Israel imaged as a dove.",
      },
    ],
  },
  33: {
    english: [
      ["And", "g1.33.1"],
      ["I", "g1.33.1"],
      ["myself", "", true],
      ["did", "g1.33.2"],
      ["not", "g1.33.2"],
      ["know", "g1.33.3"],
      ["him,", "g1.33.4"],
      ["but", "g1.33.5"],
      ["the", "g1.33.6"],
      ["one", "g1.33.7"],
      ["who", "g1.33.7"],
      ["sent", "g1.33.7"],
      ["me", "g1.33.8"],
      ["to", "g1.33.9"],
      ["baptize", "g1.33.9"],
      ["with", "g1.33.10"],
      ["water,", "g1.33.11"],
      ["he", "g1.33.12"],
      ["said", "g1.33.14"],
      ["to", "g1.33.13"],
      ["me,", "g1.33.13"],
      ["“On", "g1.33.15"],
      ["whom", "g1.33.16"],
      ["ever", "g1.33.17"],
      ["you", "g1.33.18"],
      ["see", "g1.33.18"],
      ["the", "g1.33.19"],
      ["Spirit", "g1.33.20"],
      ["descending", "g1.33.21"],
      ["and", "g1.33.22"],
      ["remaining", "g1.33.23"],
      ["upon", "g1.33.24"],
      ["him,", "g1.33.25"],
      ["this", "g1.33.26"],
      ["is", "g1.33.27"],
      ["he", "g1.33.28"],
      ["who", "g1.33.29"],
      ["baptizes", "g1.33.29"],
      ["with", "g1.33.30"],
      ["the", "g1.33.32", true],
      ["Holy", "g1.33.32"],
      ["Spirit.”", "g1.33.31"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.33.29 g1.33.31", lemma: "βαπτίζων ἐν Πνεύματι Ἁγίῳ",
        title: "Water baptism, Spirit baptism",
        body: "John’s water is the shadow; the substance is that this one **baptizes with the Holy Spirit** — the promised outpouring of God’s own life (Ezek 36:27; Joel 2:28), which this Gospel will trace to the risen Jesus (20:22). The remaining Spirit is at once the *sign* by which John recognizes him and the *gift* he will pour out.",
      },
    ],
  },
  34: {
    english: [
      ["And", "g1.34.1"],
      ["I", "g1.34.1"],
      ["have", "g1.34.2"],
      ["seen", "g1.34.2"],
      ["and", "g1.34.3"],
      ["have", "g1.34.4"],
      ["borne", "g1.34.4"],
      ["witness", "g1.34.4"],
      ["that", "g1.34.5"],
      ["this", "g1.34.6"],
      ["is", "g1.34.7"],
      ["the", "g1.34.8"],
      ["Son", "g1.34.9"],
      ["of", "g1.34.11"],
      ["God.", "g1.34.11"],
    ],
    annotations: [
      {
        kind: "text", refs: "g1.34.9", lemma: "ὁ Υἱὸς / ὁ ἐκλεκτὸς τοῦ Θεοῦ",
        title: "“Son of God” — or “Chosen One of God”?",
        body: "Some early witnesses (𝔓⁵ⱽᶦᵈ, א*, part of the Old Latin and Syriac) read **ὁ ἐκλεκτὸς τοῦ Θεοῦ**, “the *Chosen One* of God,” instead of **ὁ Υἱός**, “the *Son*.” “Chosen One” (echoing the servant of Isa 42:1) is arguably the harder reading, more easily “corrected” toward the familiar “Son.” The majority — and Nestle 1904 — read “Son,” which lets the Baptist close his testimony with the very title Nathanael will reach for in v. 49.",
      },
    ],
  },
  35: {
    english: [
      ["The", "g1.35.1"],
      ["next", "g1.35.2"],
      ["day", "g1.35.2"],
      ["again", "g1.35.3"],
      ["John", "g1.35.6"],
      ["was", "g1.35.4"],
      ["standing,", "g1.35.4"],
      ["with", "g1.35.7"],
      ["two", "g1.35.12"],
      ["of", "g1.35.8"],
      ["his", "g1.35.11"],
      ["disciples,", "g1.35.10"],
    ],
    annotations: [
    ],
  },
  36: {
    english: [
      ["and", "g1.36.1"],
      ["looking", "g1.36.2"],
      ["at", "g1.36.3"],
      ["Jesus", "g1.36.4"],
      ["as", "g1.36.5"],
      ["he", "g1.36.5"],
      ["walked,", "g1.36.5"],
      ["he", "", true],
      ["says,", "g1.36.6"],
      ["“Behold,", "g1.36.7"],
      ["the", "g1.36.8"],
      ["Lamb", "g1.36.9"],
      ["of", "g1.36.11"],
      ["God!”", "g1.36.11"],
    ],
    annotations: [
    ],
  },
  37: {
    english: [
      ["And", "g1.37.1"],
      ["the", "g1.37.3"],
      ["two", "g1.37.4"],
      ["disciples", "g1.37.5"],
      ["heard", "g1.37.2"],
      ["him", "g1.37.6"],
      ["speak,", "g1.37.7"],
      ["and", "g1.37.8"],
      ["they", "g1.37.9"],
      ["followed", "g1.37.9"],
      ["Jesus.", "g1.37.11"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.37.9", lemma: "ἠκολούθησαν",
        title: "The first following",
        body: "**ἀκολουθέω**, “follow,” is the first movement of discipleship in this Gospel, and it carries both senses at once: literally walking behind Jesus down the road, and figuratively becoming his follower. John the Baptist’s witness has done its work — it hands his own disciples over to the Lamb.",
      },
    ],
  },
  38: {
    english: [
      ["Jesus", "g1.38.4"],
      ["turned", "g1.38.1"],
      ["and,", "g1.38.5"],
      ["seeing", "g1.38.6"],
      ["them", "g1.38.7"],
      ["following,", "g1.38.8"],
      ["says", "g1.38.9"],
      ["to", "g1.38.10"],
      ["them,", "g1.38.10"],
      ["“What", "g1.38.11"],
      ["are", "g1.38.12"],
      ["you", "g1.38.12"],
      ["seeking?”", "g1.38.12"],
      ["And", "g1.38.14"],
      ["they", "g1.38.13"],
      ["said", "g1.38.15"],
      ["to", "g1.38.16"],
      ["him,", "g1.38.16"],
      ["“Rabbi”", "g1.38.17"],
      ["(which", "g1.38.18"],
      ["means,", "g1.38.19"],
      ["when", "g1.38.20"],
      ["translated,", "g1.38.20"],
      ["Teacher),", "g1.38.21"],
      ["“where", "g1.38.22"],
      ["are", "g1.38.23"],
      ["you", "g1.38.23"],
      ["staying?”", "g1.38.23"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.38.11", lemma: "Τί ζητεῖτε;",
        title: "Jesus’ first words: “What are you seeking?”",
        body: "The very first sentence Jesus speaks in this Gospel is a question — and one aimed at the reader as much as at the two disciples: **τί ζητεῖτε;** “What are you looking for?” It is the question every would-be follower must answer. (At the Gospel’s other end, the risen Jesus asks Mary almost the same thing: “Whom are you seeking?” 20:15.)",
      },
      {
        kind: "translation", refs: "g1.38.17 g1.38.21", lemma: "Ῥαββεί → Διδάσκαλε",
        title: "The evangelist as translator",
        body: "The narrator stops to gloss the Aramaic **Rabbi** (“my great one”) with the Greek **Διδάσκαλε**, “Teacher.” These bilingual asides — here, then “Messiah/Christ” (v. 41) and “Cephas/Peter” (v. 42) — reveal a writer explaining a Semitic world to Greek-speaking readers, and quietly authenticate the tradition he hands on.",
      },
    ],
  },
  39: {
    english: [
      ["He", "", true],
      ["says", "g1.39.1"],
      ["to", "g1.39.2"],
      ["them,", "g1.39.2"],
      ["“Come", "g1.39.3"],
      ["and", "g1.39.4"],
      ["you", "g1.39.5"],
      ["will", "g1.39.5"],
      ["see.”", "g1.39.5"],
      ["So", "g1.39.7"],
      ["they", "g1.39.6"],
      ["came", "g1.39.6"],
      ["and", "g1.39.8"],
      ["saw", "g1.39.9"],
      ["where", "g1.39.10"],
      ["he", "g1.39.11"],
      ["was", "g1.39.11"],
      ["staying,", "g1.39.11"],
      ["and", "g1.39.12"],
      ["they", "g1.39.15"],
      ["stayed", "g1.39.15"],
      ["with", "g1.39.13"],
      ["him", "g1.39.14"],
      ["that", "g1.39.18"],
      ["day;", "g1.39.17"],
      ["it", "", true],
      ["was", "g1.39.20"],
      ["about", "g1.39.21"],
      ["the", "", true],
      ["tenth", "g1.39.22"],
      ["hour.", "g1.39.19"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.39.3 g1.39.15 g1.39.22", lemma: "Ἔρχεσθε καὶ ὄψεσθε",
        title: "“Come and you will see” — and stay",
        body: "Jesus answers a question about *where he stays* with an invitation to *come and see* — discipleship begins not with doctrine but with going and looking. The verb **μένω** (“stay, abide”) rings through the scene: they *stayed* with him that day. And the oddly precise **tenth hour** (about 4 p.m.) reads like remembered detail — the trace of an eyewitness who never forgot the afternoon it began.",
      },
    ],
  },
  40: {
    english: [
      ["Andrew,", "g1.40.2"],
      ["the", "g1.40.3"],
      ["brother", "g1.40.4"],
      ["of", "g1.40.5"],
      ["Simon", "g1.40.5"],
      ["Peter,", "g1.40.6"],
      ["was", "g1.40.1"],
      ["one", "g1.40.7"],
      ["of", "g1.40.8"],
      ["the", "g1.40.9"],
      ["two", "g1.40.10"],
      ["who", "g1.40.11"],
      ["heard", "g1.40.12"],
      ["John", "g1.40.14"],
      ["and", "g1.40.15"],
      ["followed", "g1.40.16"],
      ["him.", "g1.40.17"],
    ],
    annotations: [
    ],
  },
  41: {
    english: [
      ["He", "g1.41.2"],
      ["first", "g1.41.3"],
      ["finds", "g1.41.1"],
      ["his", "g1.41.7"],
      ["own", "g1.41.7"],
      ["brother", "g1.41.5"],
      ["Simon", "g1.41.8"],
      ["and", "g1.41.9"],
      ["says", "g1.41.10"],
      ["to", "g1.41.11"],
      ["him,", "g1.41.11"],
      ["“We", "g1.41.12"],
      ["have", "g1.41.12"],
      ["found", "g1.41.12"],
      ["the", "g1.41.13"],
      ["Messiah”", "g1.41.14"],
      ["(which", "g1.41.15"],
      ["is,", "g1.41.16"],
      ["translated,", "g1.41.17"],
      ["Christ).", "g1.41.18"],
    ],
    annotations: [
      {
        kind: "translation", refs: "g1.41.14 g1.41.18", lemma: "Μεσσίας → Χριστός",
        title: "“Messiah,” kept in the original",
        body: "Andrew reports the discovery in the Semitic word itself — **Messiah** (Hebrew/Aramaic *māshîaḥ*, “anointed one”) — which the evangelist then renders into Greek as **Christós**. John is the only NT writer who keeps the transliterated “Messias” (here and 4:25), preserving the Jewish texture of the first confession before translating it for the wider world.",
      },
    ],
  },
  42: {
    english: [
      ["He", "", true],
      ["brought", "g1.42.1"],
      ["him", "g1.42.2"],
      ["to", "g1.42.3"],
      ["Jesus.", "g1.42.5"],
      ["Jesus", "g1.42.9"],
      ["looked", "g1.42.6"],
      ["at", "g1.42.6"],
      ["him", "g1.42.7"],
      ["and", "", true],
      ["said,", "g1.42.10"],
      ["“You", "g1.42.11"],
      ["are", "g1.42.12"],
      ["Simon", "g1.42.13"],
      ["the", "g1.42.14"],
      ["son", "g1.42.15"],
      ["of", "g1.42.16"],
      ["John;", "g1.42.16"],
      ["you", "g1.42.17"],
      ["shall", "g1.42.18"],
      ["be", "g1.42.18"],
      ["called", "g1.42.18"],
      ["Cephas”", "g1.42.19"],
      ["(which", "g1.42.20"],
      ["is", "g1.42.21"],
      ["translated", "g1.42.21"],
      ["Peter).", "g1.42.22"],
    ],
    annotations: [
      {
        kind: "translation", refs: "g1.42.19 g1.42.22", lemma: "Κηφᾶς → Πέτρος",
        title: "A new name: Kēphā / Petros",
        body: "Jesus gives Simon the Aramaic **Kēphā** (“rock”), glossed by its Greek twin **Petros**. As God renamed Abram and Jacob, the renaming assigns a destiny. John places it at the *first* meeting; Matthew ties the name to Peter’s later confession (Matt 16:18). Both keep the pun on *rock* that the English “Peter” all but hides.",
      },
    ],
  },
  43: {
    english: [
      ["The", "g1.43.1"],
      ["next", "g1.43.2"],
      ["day", "g1.43.2"],
      ["he", "", true],
      ["decided", "g1.43.3"],
      ["to", "g1.43.4"],
      ["go", "g1.43.4"],
      ["out", "g1.43.4"],
      ["to", "g1.43.5"],
      ["Galilee.", "g1.43.7"],
      ["And", "g1.43.8"],
      ["he", "", true],
      ["finds", "g1.43.9"],
      ["Philip.", "g1.43.10"],
      ["And", "g1.43.11"],
      ["Jesus", "g1.43.15"],
      ["says", "g1.43.12"],
      ["to", "g1.43.13"],
      ["him,", "g1.43.13"],
      ["“Follow", "g1.43.16"],
      ["me.”", "g1.43.17"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.43.16", lemma: "Ἀκολούθει μοι",
        title: "“Follow me”",
        body: "With Philip, Jesus for the first time issues the call *himself* — the others were brought by a witness. **Ἀκολούθει μοι** is present imperative: not a single step but a continuing “keep following me.” It is the summons that will echo to the last chapter, where it is spoken again to Peter (21:19, 22).",
      },
    ],
  },
  44: {
    english: [
      ["Now", "g1.44.2"],
      ["Philip", "g1.44.4"],
      ["was", "g1.44.1"],
      ["from", "g1.44.5"],
      ["Bethsaida,", "g1.44.6"],
      ["the", "g1.44.8"],
      ["city", "g1.44.9"],
      ["of", "g1.44.7"],
      ["Andrew", "g1.44.10"],
      ["and", "g1.44.11"],
      ["Peter.", "g1.44.12"],
    ],
    annotations: [
    ],
  },
  45: {
    english: [
      ["Philip", "g1.45.2"],
      ["finds", "g1.45.1"],
      ["Nathanael", "g1.45.4"],
      ["and", "g1.45.5"],
      ["says", "g1.45.6"],
      ["to", "g1.45.7"],
      ["him,", "g1.45.7"],
      ["“We", "g1.45.17"],
      ["have", "g1.45.17"],
      ["found", "g1.45.17"],
      ["him", "", true],
      ["of", "g1.45.8"],
      ["whom", "g1.45.8"],
      ["Moses", "g1.45.10"],
      ["wrote", "g1.45.9"],
      ["in", "g1.45.11"],
      ["the", "g1.45.12"],
      ["Law,", "g1.45.13"],
      ["and", "g1.45.14"],
      ["the", "g1.45.15"],
      ["prophets", "g1.45.16"],
      ["—", "", true],
      ["Jesus,", "g1.45.18"],
      ["son", "g1.45.19"],
      ["of", "g1.45.21"],
      ["Joseph,", "g1.45.21"],
      ["from", "g1.45.23"],
      ["Nazareth.”", "g1.45.24"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.45.9 g1.45.18 g1.45.24", lemma: "Ἰησοῦν … τὸν ἀπὸ Ναζαρέτ",
        title: "A true confession, half-right",
        body: "Philip has it exactly right — the whole of Scripture, “Moses in the Law and the prophets,” points to Jesus (cf. 5:46) — and yet half-wrong: Jesus is not really the **son of Joseph**, and his origin runs deeper than **Nazareth**. The reader, who has read the Prologue, hears the irony. Discovery here outruns understanding; that gap is where the rest of the Gospel does its work.",
      },
    ],
  },
  46: {
    english: [
      ["And", "g1.46.1"],
      ["Nathanael", "g1.46.4"],
      ["said", "g1.46.2"],
      ["to", "g1.46.3"],
      ["him,", "g1.46.3"],
      ["“Can", "g1.46.7"],
      ["anything", "g1.46.8"],
      ["good", "g1.46.9"],
      ["come", "g1.46.10"],
      ["out", "g1.46.5"],
      ["of", "g1.46.5"],
      ["Nazareth?”", "g1.46.6"],
      ["Philip", "g1.46.14"],
      ["says", "g1.46.11"],
      ["to", "g1.46.12"],
      ["him,", "g1.46.12"],
      ["“Come", "g1.46.15"],
      ["and", "g1.46.16"],
      ["see.”", "g1.46.17"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.46.6 g1.46.15", lemma: "Ἐκ Ναζαρὲτ … Ἔρχου καὶ ἴδε",
        title: "“Can anything good come from Nazareth?”",
        body: "Nazareth was a nowhere village, unmentioned in the OT or the Talmud — hence Nathanael’s scorn. Philip does not argue; he simply repeats Jesus’ own invitation, **“Come and see.”** In this Gospel doubt is answered not by proof but by encounter: go, look, and let the person settle the question.",
      },
    ],
  },
  47: {
    english: [
      ["Jesus", "g1.47.2"],
      ["saw", "g1.47.1"],
      ["Nathanael", "g1.47.4"],
      ["coming", "g1.47.5"],
      ["toward", "g1.47.6"],
      ["him", "g1.47.7"],
      ["and", "g1.47.8"],
      ["says", "g1.47.9"],
      ["of", "g1.47.10"],
      ["him,", "g1.47.11"],
      ["“Behold,", "g1.47.12"],
      ["truly", "g1.47.13"],
      ["an", "g1.47.14", true],
      ["Israelite", "g1.47.14"],
      ["in", "g1.47.15"],
      ["whom", "g1.47.16"],
      ["is", "g1.47.19"],
      ["no", "g1.47.18"],
      ["deceit!”", "g1.47.17"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.47.14 g1.47.17", lemma: "Ἰσραηλείτης … δόλος οὐκ",
        title: "An Israelite without Jacob’s guile",
        body: "The praise is a scriptural pun. **Israel** *was* Jacob — and Jacob was the man of **δόλος**, “deceit” (Gen 27:35, “your brother came with guile and took your blessing”). Nathanael is the true **Israelite** in whom there is *no* Jacob-guile: Israel as it was meant to be. The name-play quietly prepares the Jacob’s-ladder saying four verses on (v. 51).",
      },
    ],
  },
  48: {
    english: [
      ["Nathanael", "g1.48.3"],
      ["says", "g1.48.1"],
      ["to", "g1.48.2"],
      ["him,", "g1.48.2"],
      ["“How", "g1.48.4"],
      ["do", "g1.48.6"],
      ["you", "g1.48.6"],
      ["know", "g1.48.6"],
      ["me?”", "g1.48.5"],
      ["Jesus", "g1.48.8"],
      ["answered", "g1.48.7"],
      ["and", "g1.48.9"],
      ["said", "g1.48.10"],
      ["to", "g1.48.11"],
      ["him,", "g1.48.11"],
      ["“Before", "g1.48.12"],
      ["Philip", "g1.48.15"],
      ["called", "g1.48.16"],
      ["you,", "g1.48.14"],
      ["while", "g1.48.17"],
      ["you", "g1.48.17"],
      ["were", "g1.48.17"],
      ["under", "g1.48.18"],
      ["the", "g1.48.19"],
      ["fig", "g1.48.20"],
      ["tree,", "g1.48.20"],
      ["I", "g1.48.21"],
      ["saw", "g1.48.21"],
      ["you.”", "g1.48.22"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.48.20 g1.48.21", lemma: "ὑπὸ τὴν συκῆν",
        title: "“Under the fig tree”",
        body: "Sitting **under one’s fig tree** was a rabbinic picture of undisturbed study of Torah, and a prophetic image of messianic peace (Mic 4:4; Zech 3:10). Whatever Nathanael was doing there, Jesus *saw* him — with a sight that needs no introduction. The all-knowing gaze, not an argument, undoes his scepticism.",
      },
    ],
  },
  49: {
    english: [
      ["Nathanael", "g1.49.3"],
      ["answered", "g1.49.1"],
      ["him,", "g1.49.2"],
      ["“Rabbi,", "g1.49.4"],
      ["you", "g1.49.5"],
      ["are", "g1.49.6"],
      ["the", "g1.49.7"],
      ["Son", "g1.49.8"],
      ["of", "g1.49.10"],
      ["God!", "g1.49.10"],
      ["You", "g1.49.11"],
      ["are", "g1.49.13"],
      ["the", "", true],
      ["King", "g1.49.12"],
      ["of", "g1.49.15"],
      ["Israel!”", "g1.49.15"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.49.8 g1.49.12", lemma: "ὁ Υἱὸς τοῦ Θεοῦ · Βασιλεὺς τοῦ Ἰσραήλ",
        title: "“Son of God” and “King of Israel”",
        body: "Nathanael pairs two royal-messianic titles: **Son of God** (a title of the Davidic king, Ps 2:7; 2 Sam 7:14) and **King of Israel**. It is a true confession — the genuine Israelite hails Israel’s King — but still bounded by national hope. Jesus’ reply (vv. 50–51) promises he will see something far larger than a King of Israel.",
      },
    ],
  },
  50: {
    english: [
      ["Jesus", "g1.50.2"],
      ["answered", "g1.50.1"],
      ["and", "g1.50.3"],
      ["said", "g1.50.4"],
      ["to", "g1.50.5"],
      ["him,", "g1.50.5"],
      ["“Because", "g1.50.6"],
      ["I", "g1.50.7"],
      ["said", "g1.50.7"],
      ["to", "g1.50.8"],
      ["you", "g1.50.8"],
      ["that", "g1.50.9"],
      ["I", "g1.50.10"],
      ["saw", "g1.50.10"],
      ["you", "g1.50.11"],
      ["under", "g1.50.12"],
      ["the", "g1.50.13"],
      ["fig", "g1.50.14"],
      ["tree,", "g1.50.14"],
      ["do", "g1.50.15"],
      ["you", "g1.50.15"],
      ["believe?", "g1.50.15"],
      ["You", "g1.50.18"],
      ["will", "g1.50.18"],
      ["see", "g1.50.18"],
      ["greater", "g1.50.16"],
      ["things", "g1.50.16"],
      ["than", "g1.50.17"],
      ["these.", "g1.50.17"],
    ],
    annotations: [
    ],
  },
  51: {
    english: [
      ["And", "g1.51.1"],
      ["he", "", true],
      ["says", "g1.51.2"],
      ["to", "g1.51.3"],
      ["him,", "g1.51.3"],
      ["“Amen,", "g1.51.4"],
      ["amen,", "g1.51.5"],
      ["I", "g1.51.6"],
      ["say", "g1.51.6"],
      ["to", "g1.51.7"],
      ["you,", "g1.51.7"],
      ["you", "g1.51.8"],
      ["will", "g1.51.8"],
      ["see", "g1.51.8"],
      ["heaven", "g1.51.10"],
      ["opened", "g1.51.11"],
      ["and", "g1.51.12"],
      ["the", "g1.51.13"],
      ["angels", "g1.51.14"],
      ["of", "g1.51.16"],
      ["God", "g1.51.16"],
      ["ascending", "g1.51.17"],
      ["and", "g1.51.18"],
      ["descending", "g1.51.19"],
      ["upon", "g1.51.20"],
      ["the", "g1.51.21"],
      ["Son", "g1.51.22"],
      ["of", "g1.51.24"],
      ["Man.”", "g1.51.24"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g1.51.4 g1.51.5", lemma: "Ἀμὴν ἀμήν",
        title: "“Amen, amen” — a claim of authority",
        body: "The doubled **Amen, amen** (“Truly, truly”) is unique to John, where it appears 25 times, always on Jesus’ lips, prefacing a weighty pronouncement. In ordinary use *āmēn* *responds* to someone else’s words (“so be it”); Jesus uses it to *introduce his own* — an implicit claim to speak with underived authority.",
      },
      {
        kind: "concept", refs: "g1.51.17 g1.51.19 g1.51.22", lemma: "ἀγγέλους … ἐπὶ τὸν Υἱὸν τοῦ ἀνθρώπου",
        title: "Jacob’s ladder — and the Son of Man",
        body: "The picture of **angels ascending and descending** is lifted straight from Jacob’s dream at Bethel (Gen 28:12), where they move on the stairway joining heaven and earth. Jesus puts himself where the ladder stood: the **Son of Man** *is* the meeting-point of the two worlds. This is the first of John’s many “Son of Man” sayings (behind it, the heavenly figure of Dan 7:13) — and the **“you” is plural**: the promise is to all who follow.",
      },
    ],
  },
};
