// John 2 — English translation & annotations.
// english entry: [text, alignIds, supplied?]

export const CONTENT = {
  1: {
    english: [
      ["And", "g2.1.1"],
      ["on", "g2.1.2", true],
      ["the", "g2.1.2"],
      ["third", "g2.1.4 g2.1.5"],
      ["day", "g2.1.3"],
      ["there", "g2.1.7", true],
      ["was", "g2.1.7"],
      ["a", "g2.1.6", true],
      ["wedding", "g2.1.6"],
      ["at", "g2.1.8"],
      ["Cana", "g2.1.9"],
      ["in", "g2.1.10", true],
      ["Galilee,", "g2.1.11"],
      ["and", "g2.1.12"],
      ["the", "g2.1.14"],
      ["mother", "g2.1.15"],
      ["of", "g2.1.16"],
      ["Jesus", "g2.1.17"],
      ["was", "g2.1.13"],
      ["there.", "g2.1.18"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g2.1.5 g2.1.15", lemma: "τῇ ἡμέρᾳ τῇ τρίτῃ · ἡ μήτηρ",
        title: "“On the third day” — and an unnamed mother",
        body: "Counting from the call of the disciples, this is the seventh day of the Gospel’s opening week — and John pointedly dates it **“the third day,”** a phrase later readers can hardly hear without an echo of resurrection. Note too that John never names Mary: she is always **“the mother of Jesus.”** It is a deliberate reticence that keeps the focus on her son.",
      },
    ],
  },
  2: {
    english: [
      ["Now", "g2.2.2"],
      ["Jesus", "g2.2.4 g2.2.5"],
      ["also", "g2.2.3"],
      ["was", "g2.2.1"],
      ["invited", "g2.2.1"],
      ["to", "g2.2.10"],
      ["the", "g2.2.11"],
      ["wedding,", "g2.2.12"],
      ["with", "g2.2.6"],
      ["his", "g2.2.9"],
      ["disciples.", "g2.2.7 g2.2.8"],
    ],
    annotations: [
    ],
  },
  3: {
    english: [
      ["And", "g2.3.1"],
      ["when", "g2.3.2", true],
      ["the", "g2.3.3", true],
      ["wine", "g2.3.3"],
      ["ran", "g2.3.2"],
      ["short,", "g2.3.2"],
      ["the", "g2.3.5"],
      ["mother", "g2.3.6"],
      ["of", "g2.3.7"],
      ["Jesus", "g2.3.8"],
      ["says", "g2.3.4"],
      ["to", "g2.3.9"],
      ["him,", "g2.3.10"],
      ["“They", "", true],
      ["have", "g2.3.13"],
      ["no", "g2.3.12"],
      ["wine.”", "g2.3.11"],
    ],
    annotations: [
    ],
  },
  4: {
    english: [
      ["And", "g2.4.1"],
      ["Jesus", "g2.4.4 g2.4.5"],
      ["says", "g2.4.2"],
      ["to", "g2.4.3"],
      ["her,", "g2.4.3"],
      ["“Woman,", "g2.4.10"],
      ["what", "g2.4.6"],
      ["is", "", true],
      ["that", "", true],
      ["to", "g2.4.7", true],
      ["me", "g2.4.7"],
      ["and", "g2.4.8"],
      ["to", "g2.4.9", true],
      ["you?", "g2.4.9"],
      ["My", "g2.4.15"],
      ["hour", "g2.4.13 g2.4.14"],
      ["has", "", true],
      ["not", "g2.4.11"],
      ["yet", "g2.4.11"],
      ["come.”", "g2.4.12"],
    ],
    annotations: [
      {
        kind: "translation", refs: "g2.4.6 g2.4.7 g2.4.9 g2.4.10", lemma: "Τί ἐμοὶ καὶ σοί; γύναι",
        title: "“What is that to me and to you?” — not a rebuke",
        body: "The phrase **τί ἐμοὶ καὶ σοί** is a Hebrew idiom (“what to me and to you?”, 2 Sam 16:10; 1 Kgs 17:18) marking a certain *distance* between two parties — here, that Jesus will act on his Father’s timing, not his mother’s prompting. It is not rude, and neither is **γύναι**, “Woman”: a perfectly respectful address in Greek (he uses it again, tenderly, from the cross, 19:26). English “Woman” sounds colder than the Greek.",
      },
      {
        kind: "concept", refs: "g2.4.11 g2.4.13 g2.4.14", lemma: "οὔπω ἥκει ἡ ὥρα μου",
        title: "“My hour has not yet come”",
        body: "The **hour** (**ὥρα**) is one of John’s deepest threads: the appointed time of Jesus’ glorification through the cross (7:30; 8:20; 12:23; 17:1). Here at the first sign it is **“not yet”** — yet he acts anyway, giving a foretaste. The whole Gospel moves toward the hour that is, finally, *now*.",
      },
    ],
  },
  5: {
    english: [
      ["His", "g2.5.4"],
      ["mother", "g2.5.2 g2.5.3"],
      ["says", "g2.5.1"],
      ["to", "g2.5.5", true],
      ["the", "g2.5.5"],
      ["servants,", "g2.5.6"],
      ["“Whatever", "g2.5.7 g2.5.8 g2.5.9"],
      ["he", "", true],
      ["says", "g2.5.10"],
      ["to", "g2.5.11", true],
      ["you,", "g2.5.11"],
      ["do", "g2.5.12"],
      ["it.”", "g2.5.12"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g2.5.12", lemma: "Ὅ τι ἂν λέγῃ ὑμῖν, ποιήσατε",
        title: "Mary’s last recorded words",
        body: "“Do whatever he tells you” are the last words of Mary preserved in Scripture — and they echo Pharaoh’s command about Joseph in the famine: *“Go to Joseph; whatever he says to you, do”* (Gen 41:55). She does not presume to know *how* he will act; she simply hands the servants over to his word.",
      },
    ],
  },
  6: {
    english: [
      ["Now", "g2.6.2"],
      ["standing", "g2.6.12"],
      ["there", "g2.6.3"],
      ["were", "g2.6.1"],
      ["six", "g2.6.6"],
      ["stone", "g2.6.4"],
      ["water-jars,", "g2.6.5"],
      ["for", "g2.6.7"],
      ["the", "g2.6.8"],
      ["Jewish", "g2.6.10 g2.6.11"],
      ["rites", "", true],
      ["of", "", true],
      ["purification,", "g2.6.9"],
      ["each", "g2.6.14"],
      ["holding", "g2.6.13"],
      ["two", "g2.6.16"],
      ["or", "g2.6.17"],
      ["three", "g2.6.18"],
      ["measures.", "g2.6.15"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g2.6.4 g2.6.9 g2.6.15", lemma: "λίθιναι ὑδρίαι … καθαρισμόν",
        title: "Stone jars, and an extravagant amount",
        body: "The jars are **stone** because, in Jewish practice, stone vessels did not contract ritual impurity — they held water for **purification**. Each held two or three *metrētai*; six jars comes to something like **450–680 litres**. Jesus turns the water of the old rites of washing into a staggering abundance of wine — a quiet parable of what he brings.",
      },
    ],
  },
  7: {
    english: [
      ["Jesus", "g2.7.3 g2.7.4"],
      ["says", "g2.7.1"],
      ["to", "g2.7.2", true],
      ["them,", "g2.7.2"],
      ["“Fill", "g2.7.5"],
      ["the", "g2.7.6"],
      ["jars", "g2.7.7"],
      ["with", "", true],
      ["water.”", "g2.7.8"],
      ["And", "g2.7.9"],
      ["they", "", true],
      ["filled", "g2.7.10"],
      ["them", "g2.7.11"],
      ["to", "g2.7.12"],
      ["the", "", true],
      ["brim.", "g2.7.13"],
    ],
    annotations: [
    ],
  },
  8: {
    english: [
      ["And", "g2.8.1"],
      ["he", "", true],
      ["says", "g2.8.2"],
      ["to", "g2.8.3", true],
      ["them,", "g2.8.3"],
      ["“Now", "g2.8.5"],
      ["draw", "g2.8.4"],
      ["some", "", true],
      ["out", "g2.8.4", true],
      ["and", "g2.8.6"],
      ["take", "g2.8.7"],
      ["it", "", true],
      ["to", "g2.8.8", true],
      ["the", "g2.8.8"],
      ["master", "g2.8.9"],
      ["of", "", true],
      ["the", "", true],
      ["feast.”", "g2.8.9"],
      ["So", "g2.8.11"],
      ["they", "g2.8.10"],
      ["took", "g2.8.12"],
      ["it.", "", true],
    ],
    annotations: [
    ],
  },
  9: {
    english: [
      ["When", "g2.9.1"],
      ["the", "g2.9.4"],
      ["master", "g2.9.5"],
      ["of", "", true],
      ["the", "", true],
      ["feast", "g2.9.5", true],
      ["tasted", "g2.9.3"],
      ["the", "g2.9.6"],
      ["water", "g2.9.7"],
      ["now", "", true],
      ["become", "g2.9.9"],
      ["wine", "g2.9.8"],
      ["—", "", true],
      ["and", "g2.9.10"],
      ["he", "", true],
      ["did", "g2.9.11"],
      ["not", "g2.9.11"],
      ["know", "g2.9.12"],
      ["where", "g2.9.13"],
      ["it", "g2.9.14", true],
      ["came", "g2.9.14"],
      ["from,", "g2.9.14"],
      ["though", "g2.9.16"],
      ["the", "g2.9.15"],
      ["servants", "g2.9.17"],
      ["who", "g2.9.19"],
      ["had", "g2.9.20"],
      ["drawn", "g2.9.20"],
      ["the", "g2.9.21"],
      ["water", "g2.9.22"],
      ["knew", "g2.9.18"],
      ["—", "", true],
      ["the", "g2.9.26"],
      ["master", "g2.9.27"],
      ["of", "", true],
      ["the", "", true],
      ["feast", "g2.9.27", true],
      ["calls", "g2.9.23"],
      ["the", "g2.9.24"],
      ["bridegroom", "g2.9.25"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g2.9.5 g2.9.17 g2.9.9", lemma: "ᾔδει … ᾔδεισαν",
        title: "Who knew, and who did not",
        body: "John savours the irony: the **master of the feast** tasted the miracle and had no idea where it came from, while the **servants who had drawn** it *knew*. The sign is disclosed not to the important but to those who did what they were told (v. 5). The perfect participle **γεγενημένον**, “having become,” quietly states the accomplished fact: the water *is now* wine.",
      },
    ],
  },
  10: {
    english: [
      ["and", "g2.10.1"],
      ["says", "g2.10.2"],
      ["to", "g2.10.3", true],
      ["him,", "g2.10.3"],
      ["“Everyone", "g2.10.4 g2.10.5"],
      ["serves", "g2.10.10"],
      ["the", "g2.10.7"],
      ["good", "g2.10.8"],
      ["wine", "g2.10.9"],
      ["first,", "g2.10.6"],
      ["and", "g2.10.11"],
      ["the", "g2.10.14"],
      ["poorer", "g2.10.15"],
      ["wine", "", true],
      ["when", "g2.10.12"],
      ["the", "", true],
      ["guests", "", true],
      ["are", "g2.10.13"],
      ["drunk;", "g2.10.13"],
      ["but", "", true],
      ["you", "g2.10.16"],
      ["have", "g2.10.17"],
      ["kept", "g2.10.17"],
      ["the", "g2.10.18"],
      ["good", "g2.10.19"],
      ["wine", "g2.10.20"],
      ["until", "g2.10.21"],
      ["now.”", "g2.10.22"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g2.10.19 g2.10.22", lemma: "τὸν καλὸν οἶνον ἕως ἄρτι",
        title: "The best wine kept for last",
        body: "The steward means it as a compliment on catering; John means it as a parable. The world serves its best first and declines into the lesser; in Jesus the order is reversed — **the good wine is kept until now.** The abundance and the timing together announce that the long-awaited new thing has arrived, and it surpasses the old.",
      },
    ],
  },
  11: {
    english: [
      ["This,", "g2.11.1"],
      ["the", "", true],
      ["first", "g2.11.3"],
      ["of", "g2.11.4", true],
      ["his", "", true],
      ["signs,", "g2.11.5"],
      ["Jesus", "g2.11.6 g2.11.7"],
      ["did", "g2.11.2"],
      ["at", "g2.11.8"],
      ["Cana", "g2.11.9"],
      ["in", "g2.11.10", true],
      ["Galilee,", "g2.11.11"],
      ["and", "g2.11.12"],
      ["manifested", "g2.11.13"],
      ["his", "g2.11.16"],
      ["glory;", "g2.11.14 g2.11.15"],
      ["and", "g2.11.17"],
      ["his", "g2.11.23"],
      ["disciples", "g2.11.21 g2.11.22"],
      ["believed", "g2.11.18"],
      ["in", "g2.11.19"],
      ["him.", "g2.11.20"],
    ],
    annotations: [
      {
        kind: "concept", refs: "g2.11.3 g2.11.5 g2.11.15", lemma: "ἀρχὴν τῶν σημείων … τὴν δόξαν",
        title: "The first of the “signs”",
        body: "John never calls Jesus’ miracles “wonders” or “mighty works”; they are **σημεῖα**, *signs* — pointers beyond themselves to who he is. This is the **first** of seven such signs in the Gospel. And its result is exactly what 1:14 promised: he **“manifested his glory,”** and those who saw **believed into him** — the response the whole book is written to evoke (20:30–31).",
      },
    ],
  },
};
