// English glosses by lemma. Extend when a new chapter adds vocabulary.
export const GLOSS_EN = {
  "Βηθανία": "Bethany",
  "Βηθσαϊδά": "Bethsaida",
  "Γαλιλαία": "Galilee",
  "Κανά": "Cana",
  "Κηφᾶς": "Cephas",
  "Λευίτης": "Levite",
  "Μεσσίας": "Messiah",
  "Μωϋσῆς": "Moses",
  "Ναζαρά": "Nazareth",
  "Ναθαναήλ": "Nathanael",
  "Πέτρος": "Peter",
  "Σίμων": "Simon",
  "Φίλιππος": "Philip",
  "Φαρισαῖος": "Pharisee",
  "Χριστός": "Christ, Anointed",
  "αἴρω": "to take away, lift up",
  "αἷμα": "blood",
  "αὐτός": "he, it, same",
  "βαπτίζω": "to baptize",
  "βασιλεύς": "king",
  "βλέπω": "to see, look",
  "βοάω": "to cry out",
  "γάμος": "wedding",
  "γίνομαι": "to become, come to be",
  "γεμίζω": "to fill",
  "γεννάω": "to beget, give birth",
  "γεύομαι": "to taste",
  "γινώσκω": "to know",
  "γράφω": "to write",
  "γυνή": "woman",
  "δέ": "but, and",
  "δέκατος": "tenth",
  "δίδωμι": "to give",
  "διά": "through, on account of",
  "διάκονος": "servant",
  "διδάσκαλος": "teacher",
  "δόλος": "deceit, guile",
  "δόξα": "glory",
  "δύναμαι": "to be able",
  "δύο": "two",
  "εἰ": "if",
  "εἰμί": "to be",
  "εἰς": "into, to",
  "εἷς": "one",
  "εὐθύνω": "to make straight",
  "εὑρίσκω": "to find",
  "ζητέω": "to seek",
  "ζωή": "life",
  "θέλημα": "will",
  "θέλω": "to wish, will",
  "θεάομαι": "to behold, gaze at",
  "θεός": "God",
  "καί": "and",
  "καθαρισμός": "purification",
  "καθώς": "just as",
  "καλέω": "to call",
  "καλός": "good, fine",
  "κατά": "according to, against",
  "καταβαίνω": "to come down",
  "καταλαμβάνω": "seized / grasped",
  "κεῖμαι": "to lie, be placed",
  "κράζω": "to cry out",
  "κόλπος": "bosom, side",
  "κόσμος": "world",
  "κύριος": "lord",
  "κἀγώ": "and I, I too",
  "λέγω": "to say",
  "λίθινος": "of stone",
  "λαλέω": "to speak",
  "λαμβάνω": "to take, receive",
  "λόγος": "word",
  "λύω": "to loose, untie",
  "μέγας": "great",
  "μένω": "to remain, abide",
  "μέσος": "middle, midst",
  "μήτηρ": "mother",
  "μαθητής": "disciple",
  "μαρτυρέω": "to bear witness",
  "μαρτυρία": "testimony",
  "μεθερμηνεύω": "to translate",
  "μεθύω": "to be drunk",
  "μετρητής": "measure (metretes)",
  "μονογενής": "only, only-begotten",
  "νυμφίος": "bridegroom",
  "νόμος": "law",
  "νῦν": "now",
  "οἶδα": "to know",
  "οἶνος": "wine",
  "οὐ": "not",
  "οὐδέ": "and not, nor",
  "οὐδείς": "no one",
  "οὐρανός": "heaven, sky",
  "οὔπω": "not yet",
  "οὖν": "therefore, then",
  "οὗτος": "this one",
  "πάλιν": "again",
  "πέμπω": "to send",
  "πέραν": "beyond, across",
  "παρά": "from, beside",
  "παραλαμβάνω": "to receive, take",
  "πατήρ": "father",
  "περί": "concerning, about",
  "περιπατέω": "to walk",
  "περιστερά": "dove",
  "πιστεύω": "to believe, trust",
  "πλήρης": "full",
  "πλήρωμα": "fullness",
  "πνεῦμα": "spirit, breath",
  "ποιέω": "to do, make",
  "πού": "somewhere",
  "ποῦ": "where?",
  "προφήτης": "prophet",
  "πρό": "before",
  "πρός": "to, toward, with",
  "πρῶτος": "first",
  "πόθεν": "from where",
  "πόλις": "city",
  "πώποτε": "ever, at any time",
  "πᾶς": "all, every",
  "σάρξ": "flesh",
  "σεαυτοῦ": "yourself",
  "σημεῖον": "sign",
  "σκηνόω": "to pitch a tent, dwell",
  "σκοτία": "darkness",
  "στήκω": "to stand",
  "στρέφω": "to turn",
  "συκῆ": "fig tree",
  "σύ": "you",
  "τέκνον": "child",
  "τίθημι": "to put, place",
  "τίς": "who? what?",
  "τηρέω": "to keep",
  "τρίτος": "third",
  "τρεῖς": "three",
  "τὶς": "someone, a certain",
  "υἱός": "son",
  "φέρω": "to carry, bring",
  "φαίνω": "shines",
  "φανερόω": "to reveal",
  "φημί": "to say",
  "φωνέω": "to call",
  "φωνή": "voice, sound",
  "φωτίζω": "to give light to",
  "φῶς": "light",
  "χάρις": "grace, favor",
  "χωρέω": "to hold, contain",
  "χωρίς": "apart from",
  "ἀγαθός": "good",
  "ἀδελφός": "brother",
  "ἀκολουθέω": "to follow",
  "ἀκούω": "to hear",
  "ἀλήθεια": "truth",
  "ἀληθινός": "true, genuine",
  "ἀληθῶς": "truly",
  "ἀλλά": "but",
  "ἀμήν": "amen, truly",
  "ἀμνός": "lamb",
  "ἀνά": "each, apiece",
  "ἀνήρ": "man, husband",
  "ἀναβαίνω": "to go up",
  "ἀνοίγω": "to open",
  "ἀντί": "instead of, for",
  "ἀντλέω": "to draw (water)",
  "ἀποκρίνομαι": "to answer",
  "ἀποστέλλω": "to send (out)",
  "ἀπό": "from",
  "ἀπόκρισις": "answer",
  "ἀρνέομαι": "to deny",
  "ἀρχή": "beginning",
  "ἀρχιτρίκλινος": "master of the feast",
  "ἁμαρτία": "sin",
  "ἄγγελος": "angel, messenger",
  "ἄγω": "to lead, bring",
  "ἄν": "(untranslatable particle)",
  "ἄνθρωπος": "human being",
  "ἄνω": "up, to the brim",
  "ἄξιος": "worthy",
  "ἄρτι": "now, just now",
  "ἅγιος": "holy",
  "Ἀνδρέας": "Andrew",
  "ἐγώ": "I",
  "ἐκ": "out of, from",
  "ἐκεῖ": "there",
  "ἐκεῖνος": "that one",
  "ἐλάσσων": "lesser, inferior",
  "ἐμβλέπω": "to look at",
  "ἐν": "in",
  "ἐξέρχομαι": "to go out",
  "ἐξηγέομαι": "to explain, make known",
  "ἐξουσία": "authority, right",
  "ἐπί": "upon, on",
  "ἐπαύριον": "the next day",
  "ἐρωτάω": "to ask",
  "ἑρμηνεύω": "to translate, interpret",
  "ἔμπροσθεν": "before, ahead of",
  "ἔρημος": "wilderness, desert",
  "ἔρχομαι": "to come, go",
  "ἔχω": "to have",
  "ἕξ": "six",
  "ἕως": "until",
  "ἡμέρα": "day",
  "ἤ": "or",
  "ἥκω": "to have come",
  "Ἠλίας": "Elijah",
  "Ἠσαΐας": "Isaiah",
  "ἱερεύς": "priest",
  "ἱμάς": "strap, thong",
  "ἴδιος": "one’s own",
  "ἵνα": "so that, in order that",
  "ἵστημι": "to stand",
  "Ἰησοῦς": "Jesus",
  "Ἰορδάνης": "Jordan",
  "Ἰουδαῖος": "Judean, Jew",
  "Ἰσραήλ": "Israel",
  "Ἰσραηλίτης": "Israelite",
  "Ἰωάννης": "John",
  "Ἰωσήφ": "Joseph",
  "Ἱεροσόλυμα": "Jerusalem",
  "ὀπίσω": "after, behind",
  "ὁ": "the",
  "ὁδός": "way, road",
  "ὁμολογέω": "to confess, acknowledge",
  "ὁράω": "to see",
  "ὄνομα": "name",
  "ὅπου": "where",
  "ὅς": "who, which",
  "ὅσος": "as many as",
  "ὅταν": "whenever",
  "ὅτε": "when",
  "ὅτι": "that, because",
  "ὑδρία": "water-jar",
  "ὑπέρ": "above, on behalf of",
  "ὑποκάτω": "under, beneath",
  "ὑπό": "under, by",
  "ὑπόδημα": "sandal",
  "ὑστερέω": "to lack, run short",
  "ὕδωρ": "water",
  "ὡς": "as, like",
  "ὥρα": "hour",
  "ῥαββί": "rabbi",
  "μετά": "with, after", "Καφαρναούμ": "Capernaum", "πολύς": "much, many", "ἐγγύς": "near",
  "πάσχα": "Passover", "ἱερός": "sacred; temple", "πωλέω": "to sell", "βοῦς": "ox, cattle",
  "πρόβατον": "sheep", "κερματιστής": "money-changer", "κάθημαι": "to sit", "φραγέλλιον": "whip",
  "σχοινίον": "cord, rope", "ἐκβάλλω": "to drive out", "τέ": "and, both", "κολλυβιστής": "money-changer",
  "ἐκχέω": "to pour out", "κέρμα": "coin", "τράπεζα": "table", "ἀνατρέπω": "to overturn",
  "ἐντεῦθεν": "from here", "μή": "not", "οἶκος": "house", "ἐμπόριον": "house of trade",
  "μιμνῄσκω": "to remember", "ζῆλος": "zeal", "κατεσθίω": "to consume, devour", "δείκνυμι": "to show",
  "ναός": "temple, sanctuary", "ἐγείρω": "to raise", "τεσσεράκοντα": "forty", "ἔτος": "year",
  "οἰκοδομέω": "to build", "σῶμα": "body", "νεκρός": "dead", "γραφή": "Scripture", "ἑορτή": "feast",
  "θεωρέω": "to observe, behold", "ἑαυτοῦ": "himself", "χρεία": "need", "γάρ": "for, because",
  // Chapter 3
  "Νικόδημος": "Nicodemus", "ἄρχων": "ruler", "νύξ": "night", "ἐάν": "if",
  "ἄνωθεν": "from above; again", "βασιλεία": "kingdom", "πῶς": "how", "γέρων": "old man",
  "κοιλία": "womb, belly", "δεύτερος": "second", "εἰσέρχομαι": "to enter", "θαυμάζω": "to marvel, be amazed",
  "δεῖ": "it is necessary, must", "πνέω": "to blow", "ὑπάγω": "to go, depart", "οὕτω": "thus, in this way",
  "ἐπίγειος": "earthly", "ἐπουράνιος": "heavenly", "ὑψόω": "to lift up, exalt", "ὄφις": "serpent",
  "αἰώνιος": "eternal", "ἀγαπάω": "to love", "ὥστε": "so that", "ἀπόλλυμι": "to perish, destroy",
  "κρίνω": "to judge, condemn", "σῴζω": "to save", "ἤδη": "already, now", "κρίσις": "judgment",
  "μᾶλλον": "rather, more", "σκότος": "darkness", "πονηρός": "evil, wicked", "ἔργον": "work, deed",
  "φαῦλος": "worthless, wicked", "πράσσω": "to do, practise", "μισέω": "to hate", "ἐλέγχω": "to expose, convict",
  "ἐργάζομαι": "to work, do", "γῆ": "earth, land", "διατρίβω": "to stay, remain", "Αἰνών": "Aenon",
  "Σαλείμ": "Salim", "παραγίνομαι": "to come, arrive", "βάλλω": "to throw, cast", "φυλακή": "prison, guard",
  "ζήτησις": "dispute, discussion", "νύμφη": "bride", "φίλος": "friend", "χαρά": "joy",
  "χαίρω": "to rejoice", "ἐμός": "my, mine", "πληρόω": "to fill, fulfil", "αὐξάνω": "to increase, grow",
  "ἐλαττόω": "to decrease, grow less", "ἐπάνω": "above, over", "σφραγίζω": "to seal, certify", "ἀληθής": "true",
  "ῥῆμα": "word, saying", "μέτρον": "measure", "χείρ": "hand", "ἀπειθέω": "to disobey, refuse to believe",
  "ὀργή": "wrath, anger",
  // Chapter 4
  "καίτοιγε": "although, and yet", "ἀφίημι": "to leave, let go", "Ἰουδαία": "Judea", "ἀπέρχομαι": "to go away",
  "διέρχομαι": "to pass through", "Σαμάρεια": "Samaria", "Συχάρ": "Sychar", "πλησίον": "near",
  "χωρίον": "plot of land, field", "Ἰακώβ": "Jacob", "πηγή": "spring, well", "κοπιάω": "to grow weary, toil",
  "ὁδοιπορία": "journey", "καθέζομαι": "to sit down", "ἕκτος": "sixth", "πίνω": "to drink",
  "τροφή": "food", "ἀγοράζω": "to buy", "Σαμαρῖτις": "Samaritan woman", "αἰτέω": "to ask, request",
  "συγχράομαι": "to associate with", "Σαμαρίτης": "Samaritan", "δωρεά": "gift", "ζάω": "to live",
  "οὔτε": "neither, nor", "ἄντλημα": "bucket", "φρέαρ": "well, cistern", "βαθύς": "deep",
  "θρέμμα": "livestock", "διψάω": "to thirst", "αἰών": "age; forever", "ἅλλομαι": "to leap, well up",
  "μηδέ": "nor, not even", "ἐνθάδε": "here", "καλῶς": "well, rightly", "πέντε": "five",
  "εἶπον": "to say (aor. of λέγω)", "ὄρος": "mountain", "προσκυνέω": "to worship, bow down", "τόπος": "place",
  "σωτηρία": "salvation", "προσκυνητής": "worshiper", "τοιοῦτος": "such", "ἀναγγέλλω": "to announce, declare",
  "ἅπας": "all, everything", "μέντοι": "however, yet", "δεῦτε": "come!", "μήτι": "(question expecting “no”)",
  "μεταξύ": "between; meanwhile", "ἐσθίω": "to eat", "βρῶσις": "food, eating", "ἀλλήλων": "one another",
  "βρῶμα": "food", "τελειόω": "to complete, finish", "ἔτι": "still, yet", "τετράμηνος": "four months",
  "θερισμός": "harvest", "ἐπαίρω": "to lift up", "ὀφθαλμός": "eye", "χώρα": "field, region",
  "λευκός": "white", "θερίζω": "to reap", "μισθός": "wages, reward", "συνάγω": "to gather",
  "καρπός": "fruit", "σπείρω": "to sow", "ὁμοῦ": "together", "ἄλλος": "other, another",
  "κόπος": "labor, toil", "οὐκέτι": "no longer", "σός": "your", "λαλιά": "speech, telling",
  "σωτήρ": "savior", "ἐκεῖθεν": "from there", "πατρίς": "hometown", "τιμή": "honor",
  "δέχομαι": "to receive, welcome", "Γαλιλαῖος": "Galilean", "βασιλικός": "royal official", "ἀσθενέω": "to be sick",
  "ἰάομαι": "to heal", "μέλλω": "to be about to", "ἀποθνῄσκω": "to die", "τέρας": "wonder, portent",
  "πρίν": "before", "παιδίον": "child", "πορεύομαι": "to go, proceed", "δοῦλος (II)": "servant, slave",
  "ὑπαντάω": "to meet", "παῖς": "boy, servant", "πυνθάνομαι": "to inquire, ask", "κομψότερον": "better (in health)",
  "ἐχθές": "yesterday", "ἕβδομος": "seventh", "πυρετός": "fever", "οἰκία": "household, house", "ὅλος": "whole, all",
  // Chapter 5
  "προβατικός": "of sheep (Sheep Gate)", "κολυμβήθρα": "pool", "ἐπιλέγω": "to call, name", "Ἑβραϊστί": "in Hebrew/Aramaic",
  "Βηθζαθά": "Bethzatha", "στοά": "colonnade, porch", "κατάκειμαι": "to lie down", "πλῆθος": "multitude, crowd",
  "τυφλός": "blind", "χωλός": "lame", "ξηρός": "withered, paralysed", "ἐκδέχομαι": "to wait for, expect",
  "κίνησις": "moving, stirring", "καιρός": "appointed time, season", "ταράσσω": "to stir up, trouble", "ἐμβαίνω": "to step in",
  "ταραχή": "stirring, disturbance", "ὑγιής": "well, whole, healthy", "δήποτε": "whatever", "κατέχω": "to hold fast, afflict",
  "νόσημα": "disease", "τριάκοντα": "thirty", "ὀκτώ": "eight", "ἀσθένεια": "weakness, illness",
  "χρόνος": "time", "κράβαττος": "mat, pallet", "εὐθέως": "at once, immediately", "σάββατον": "Sabbath",
  "θεραπεύω": "to heal, cure", "ἔξεστι(ν)": "it is lawful", "ἐκνεύω": "to withdraw, slip away", "ὄχλος": "crowd",
  "μηκέτι": "no longer, no more", "ἁμαρτάνω": "to sin", "χείρων": "worse", "διώκω": "to pursue, persecute",
  "ἀποκτείνω": "to kill", "μόνος": "only, alone", "ἴσος": "equal", "ὁμοίως": "likewise",
  "φιλέω": "to love, befriend", "ὥσπερ": "just as", "ζῳοποιέω": "to give life", "τιμάω": "to honour",
  "μεταβαίνω": "to pass over, cross", "θάνατος": "death", "μνημεῖον": "tomb", "ἐκπορεύομαι": "to come out",
  "ἀνάστασις": "resurrection", "ἐμαυτοῦ": "myself", "δίκαιος": "just, righteous", "λύχνος": "lamp",
  "καίω": "to burn, kindle", "ἀγαλλιάω": "to rejoice, exult", "εἶδος": "form, appearance", "ἐραυνάω": "to search",
  "δοκέω": "to think, suppose", "ἀγάπη": "love", "κατηγορέω": "to accuse", "ἐλπίζω": "to hope", "γράμμα": "writing, letter",
  // Chapter 6
  "θάλασσα": "sea", "Τιβεριάς": "Tiberias", "ἀνέρχομαι": "to go up", "ἄρτος": "bread, loaf",
  "πειράζω": "to test, tempt", "διακόσιοι": "two hundred", "δηνάριον": "denarius", "ἀρκέω": "to suffice",
  "ἕκαστος": "each", "βραχύς": "little, short", "παιδάριον": "little boy", "ὧδε": "here",
  "κρίθινος": "of barley", "ὀψάριον": "fish", "τοσοῦτος": "so many, so great", "ἀναπίπτω": "to recline, sit down",
  "χόρτος": "grass", "ἀριθμός": "number", "πεντακισχίλιοι": "five thousand", "εὐχαριστέω": "to give thanks",
  "διαδίδωμι": "to distribute", "ἀνάκειμαι": "to recline (at table)", "ἐμπίπλημι": "to fill, satisfy", "περισσεύω": "to be left over, abound",
  "κλάσμα": "fragment, piece", "δώδεκα": "twelve", "κόφινος": "basket", "βιβρώσκω": "to eat",
  "ἁρπάζω": "to seize, snatch", "ἀναχωρέω": "to withdraw", "ὄψιος": "evening, late", "πλοῖον": "boat",
  "ἄνεμος": "wind", "διεγείρω": "to stir up, arouse", "ἐλαύνω": "to row, drive", "στάδιον": "stadion (~185 m)",
  "εἴκοσι": "twenty", "φοβέω": "to fear", "πλοιάριον": "small boat", "συνεισέρχομαι": "to enter with",
  "πότε": "when", "χορτάζω": "to fill, satisfy", "μάννα": "manna", "πάντοτε": "always",
  "πεινάω": "to hunger", "ἔξω": "out, outside", "ἀνίστημι": "to raise up", "ἔσχατος": "last",
  "γογγύζω": "to grumble, murmur", "ἕλκω": "to draw, drag", "διδακτός": "taught", "μανθάνω": "to learn",
  "μάχομαι": "to fight, quarrel", "τρώγω": "to gnaw, chew, eat", "πόσις": "drink", "κἀκεῖνος": "and he, that one also",
  "συναγωγή": "synagogue", "διδάσκω": "to teach", "σκληρός": "hard, harsh", "σκανδαλίζω": "to offend, cause to stumble",
  "πρότερος": "former, before", "ὠφελέω": "to profit, help", "παραδίδωμι": "to hand over, betray", "ἐκλέγω": "to choose",
  "διάβολος": "devil, slanderer", "Ἰούδας": "Judas", "Ἰσκαριώθ": "Iscariot",
  // Chapter 7
  "σκηνοπηγία": "Feast of Tabernacles", "κρυπτός": "hidden, secret", "παρρησία": "openness, boldness", "πάρειμι": "to be present, have come",
  "ὑμέτερος": "your", "ἕτοιμος": "ready", "τότε": "then", "φανερῶς": "openly",
  "γογγυσμός": "muttering, murmuring", "μέν": "on the one hand", "πλανάω": "to lead astray, deceive", "φόβος": "fear",
  "μεσόω": "to be in the middle", "διδαχή": "teaching", "πότερον": "whether", "ἀδικία": "unrighteousness, falsehood",
  "δαιμόνιον": "demon", "περιτομή": "circumcision", "περιτέμνω": "to circumcise", "χολάω": "to be angry",
  "ὄψις": "appearance, face", "Ἱεροσολυμίτης": "a person of Jerusalem", "πιάζω": "to seize, arrest", "ἐπιβάλλω": "to lay on",
  "ἀρχιερεύς": "chief priest", "ὑπηρέτης": "officer, attendant", "μικρός": "little, small", "διασπορά": "Dispersion, Diaspora",
  "Ἕλλην": "Greek", "ποταμός": "river", "ῥέω": "to flow", "οὐδέπω": "not yet",
  "δοξάζω": "to glorify", "σπέρμα": "seed, offspring", "Δαυίδ": "David", "Βηθλέεμ": "Bethlehem",
  "κώμη": "village", "σχίσμα": "division, split", "οὐδέποτε": "never", "ἐπάρατος": "accursed",
  // Chapter 8
  "ἐλαία": "olive (tree)", "ὄρθρος": "dawn, early morning", "λαός": "people", "καθίζω": "to sit down",
  "γραμματεύς": "scribe", "μοιχεία": "adultery", "ἐπαυτοφώρῳ": "in the very act", "μοιχεύω": "to commit adultery",
  "ἐντέλλομαι": "to command", "λιθοβολέω": "to stone", "κάτω": "down, below", "κύπτω": "to bend down, stoop",
  "δάκτυλος": "finger", "ἐπιμένω": "to persist, continue", "ἀνακύπτω": "to straighten up", "ἀναμάρτητος": "without sin",
  "λίθος": "stone", "συνείδησις": "conscience", "καθεῖς": "one by one", "ἄρχω": "to begin, rule",
  "πρεσβύτερος": "elder", "καταλείπω": "to leave behind", "μηδείς": "no one", "πλήν": "except",
  "κατήγορος": "accuser", "κατακρίνω": "to condemn", "κἄν": "even if, and if", "γαζοφυλάκιον": "treasury",
  "ἀρεστός": "pleasing", "ἐλευθερόω": "to set free", "Ἀβραάμ": "Abraham", "δουλεύω": "to serve, be a slave",
  "ἐλεύθερος": "free", "ὄντως": "really, indeed", "πορνεία": "sexual immorality", "ἐπιθυμία": "desire, lust",
  "ἀνθρωποκτόνος": "murderer", "ψεῦδος": "lie, falsehood", "ψεύστης": "liar", "ἀτιμάζω": "to dishonour",
  "ὅστις": "whoever, who", "ὅμοιος": "like, similar", "πεντήκοντα": "fifty", "κρύπτω": "to hide",
  // Chapter 9
  "παράγω": "to pass by", "γενετή": "birth", "γονεύς": "parent", "πτύω": "to spit",
  "χαμαί": "on the ground", "πηλός": "mud, clay", "πτύσμα": "saliva, spittle", "ἐπιτίθημι": "to put on, lay on",
  "νίπτω": "to wash", "Σιλωάμ": "Siloam", "γείτων": "neighbour", "προσαίτης": "beggar",
  "προσαιτέω": "to beg", "οὐχί": "no, not (emphatic)", "ἐπιχρίω": "to smear on, anoint", "ἀναβλέπω": "to receive sight, look up",
  "ποτέ": "once, formerly", "ἁμαρτωλός": "sinner, sinful", "ἡλικία": "age, maturity", "συντίθημι": "to agree, arrange",
  "ἀποσυνάγωγος": "put out of the synagogue", "ἐπερωτάω": "to ask, question", "λοιδορέω": "to revile, insult", "θαυμαστός": "amazing, marvellous",
  "θεοσεβής": "God-fearing, devout", "κρίμα": "judgement",
  // Chapter 10
  "θύρα": "door, gate", "αὐλή": "courtyard, fold", "ἀλλαχόθεν": "from another place", "κλέπτης": "thief",
  "λῃστής": "robber, bandit", "ποιμήν": "shepherd", "θυρωρός": "doorkeeper, gatekeeper", "ἐξάγω": "to lead out",
  "ἀλλότριος": "stranger, another's", "φεύγω": "to flee", "παροιμία": "figure of speech, proverb", "νομή": "pasture",
  "κλέπτω": "to steal", "θύω": "to kill, sacrifice", "περισσός": "abundant, more than enough", "ψυχή": "life, soul",
  "μισθωτός": "hired hand", "λύκος": "wolf", "σκορπίζω": "to scatter", "μέλει": "it is a care, it matters",
  "ποίμνη": "flock", "ἐντολή": "commandment, charge", "μαίνομαι": "to be out of one's mind", "δαιμονίζομαι": "to be demon-possessed",
  "ἐγκαίνια": "Feast of Dedication", "χειμών": "winter", "Σολομών": "Solomon", "κυκλόω": "to surround, encircle",
  "βαστάζω": "to pick up, carry", "λιθάζω": "to stone", "ποῖος": "what kind of, which", "βλασφημία": "blasphemy",
  "ἁγιάζω": "to consecrate, make holy", "βλασφημέω": "to blaspheme",
  // Chapter 11
  "Λάζαρος": "Lazarus", "Μαρία": "Mary", "Μάρθα": "Martha", "ἀδελφή": "sister",
  "ἀλείφω": "to anoint", "μύρον": "ointment, perfume", "ἐκμάσσω": "to wipe", "πούς": "foot",
  "θρίξ": "hair", "ἔπειτα": "then, afterward", "προσκόπτω": "to stumble", "κοιμάομαι": "to fall asleep, sleep",
  "ἐξυπνίζω": "to wake up", "κοίμησις": "sleep, repose", "ὕπνος": "sleep", "Θωμᾶς": "Thomas",
  "Δίδυμος": "Twin (Didymus)", "συμμαθητής": "fellow disciple", "τέσσαρες": "four", "δεκαπέντε": "fifteen",
  "παραμυθέομαι": "to console, comfort", "ναί": "yes", "λάθρᾳ": "secretly, quietly", "ταχύς": "quick",
  "ταχέως": "quickly", "κλαίω": "to weep", "πίπτω": "to fall", "αὐτοῦ": "there, in that place",
  "συνέρχομαι": "to come together, accompany", "ἐμβριμάομαι": "to be deeply moved, groan", "δακρύω": "to shed tears", "σπήλαιον": "cave",
  "ἐπίκειμαι": "to lie on, be placed against", "τελευτάω": "to die, come to an end", "ὄζω": "to give off an odor, stink", "τεταρταῖος": "on the fourth day",
  "περιΐστημι": "to stand around", "κραυγάζω": "to cry out", "δεῦρο": "come here!", "θνῄσκω": "to die",
  "δέω": "to bind", "κειρία": "grave-band, linen strip", "σουδάριον": "face-cloth, napkin", "περιδέω": "to bind around, wrap",
  "συνέδριον": "council, Sanhedrin", "Ῥωμαῖος": "Roman", "ἔθνος": "nation", "Καϊάφας": "Caiaphas",
  "ἐνιαυτός": "year", "λογίζομαι": "to reckon, consider", "συμφέρω": "to be better, be profitable", "προφητεύω": "to prophesy",
  "διασκορπίζω": "to scatter abroad", "βουλεύω": "to plan, resolve", "Ἐφραίμ": "Ephraim", "κἀκεῖ": "and there",
  "ἁγνίζω": "to purify", "μηνύω": "to report, disclose", "ὅπως": "so that, in order that",
  // Chapter 12
  "δεῖπνον": "dinner, supper", "διακονέω": "to serve, wait on", "σύν": "with", "λίτρα": "pound (Roman)",
  "νάρδος": "nard, spikenard", "πιστικός": "pure, genuine", "πολύτιμος": "very costly", "ὀσμή": "fragrance, odor",
  "πιπράσκω": "to sell", "τριακόσιοι": "three hundred", "πτωχός": "poor, beggar", "γλωσσόκομον": "moneybag, purse",
  "ἐνταφιασμός": "burial, preparation for burial", "βάϊον": "palm branch", "φοῖνιξ": "palm tree", "ὑπάντησις": "a meeting",
  "ὡσαννά": "Hosanna (save now!)", "εὐλογέω": "to bless", "ὀνάριον": "young donkey", "θυγάτηρ": "daughter",
  "Σιών": "Zion", "πῶλος": "colt, foal", "ὄνος": "donkey", "προσέρχομαι": "to come to, approach",
  "κόκκος": "grain, seed", "σῖτος": "wheat, grain", "φυλάσσω": "to guard, keep", "βροντή": "thunder",
  "σημαίνω": "to signify, indicate", "ἀκοή": "report, hearing, message", "βραχίων": "arm", "ἀποκαλύπτω": "to reveal",
  "τυφλόω": "to blind", "πωρόω": "to harden", "καρδία": "heart", "νοέω": "to understand, perceive",
  "ὅμως": "nevertheless, yet", "ἤπερ": "than", "ἀθετέω": "to reject, set aside",
  // Chapter 13
  "τέλος": "end, completion", "ἱμάτιον": "garment, cloak", "λέντιον": "towel", "διαζώννυμι": "to gird, tie around",
  "εἶτα": "then, next", "νιπτήρ": "basin", "μέρος": "part, share", "κεφαλή": "head",
  "λούω": "to bathe, wash", "καθαρός": "clean, pure", "ὀφείλω": "to owe, ought", "ὑπόδειγμα": "example, pattern",
  "ἀπόστολος": "one sent, apostle", "μακάριος": "blessed, happy", "πτέρνα": "heel", "ἀπορέω": "to be at a loss, perplexed",
  "νεύω": "to nod, motion", "στῆθος": "chest, breast", "βάπτω": "to dip", "ψωμίον": "morsel, piece of bread",
  "Σατανᾶς": "Satan", "ἐπεί": "since, because", "τεκνίον": "little child", "καινός": "new",
  "ὕστερος": "later, afterward", "ἀλέκτωρ": "rooster, cock", "τρίς": "three times",
  // Chapter 14
  "μονή": "dwelling place, room", "ἑτοιμάζω": "to prepare", "παράκλητος": "Helper, Advocate, Comforter", "ὀρφανός": "orphan",
  "ἐμφανίζω": "to manifest, make known", "ὑπομιμνῄσκω": "to remind, bring to remembrance", "εἰρήνη": "peace", "δειλιάω": "to be afraid, be cowardly",
  // Chapter 15
  "ἄμπελος": "vine", "γεωργός": "farmer, vinedresser", "κλῆμα": "branch", "καθαίρω": "to prune, cleanse",
  "ξηραίνω": "to wither, dry up", "πῦρ": "fire", "γνωρίζω": "to make known", "μνημονεύω": "to remember",
  "πρόφασις": "excuse, pretext", "δωρεάν": "without cause, freely, for nothing",
  // Chapter 16
  "λατρεία": "service, worship", "προσφέρω": "to offer, present", "λύπη": "sorrow, grief", "δικαιοσύνη": "righteousness",
  "ὁδηγέω": "to guide, lead", "θρηνέω": "to lament, mourn", "λυπέω": "to grieve, cause sorrow", "τίκτω": "to give birth",
  "θλῖψις": "affliction, tribulation", "ἀπαγγέλλω": "to announce, report", "θαρσέω": "to take heart, be of good cheer", "νικάω": "to conquer, overcome",
  // Chapter 17
  "ἀπώλεια": "destruction, ruin", "καταβολή": "foundation, beginning",
};
