// English glosses by lemma. Extend when a new chapter adds vocabulary.
export const GLOSS_EN = {
  "Βηθανία": "Bethany",
  "Βηθσαϊδά": "Bethsaida",
  "Γαλιλαία": "Galilee",
  "Κανά": "Cana",
  "Κηφᾶς": "Cephas",
  "Λευίτης": "Levite",
  "Μεσσίας": "Messiah",
  "Μωϋσῆς": "Moses",
  "Ναζαρά": "Nazareth",
  "Ναθαναήλ": "Nathanael",
  "Πέτρος": "Peter",
  "Σίμων": "Simon",
  "Φίλιππος": "Philip",
  "Φαρισαῖος": "Pharisee",
  "Χριστός": "Christ, Anointed",
  "αἴρω": "to take away, lift up",
  "αἷμα": "blood",
  "αὐτός": "he, it, same",
  "βαπτίζω": "to baptize",
  "βασιλεύς": "king",
  "βλέπω": "to see, look",
  "βοάω": "to cry out",
  "γάμος": "wedding",
  "γίνομαι": "to become, come to be",
  "γεμίζω": "to fill",
  "γεννάω": "to beget, give birth",
  "γεύομαι": "to taste",
  "γινώσκω": "to know",
  "γράφω": "to write",
  "γυνή": "woman",
  "δέ": "but, and",
  "δέκατος": "tenth",
  "δίδωμι": "to give",
  "διά": "through, on account of",
  "διάκονος": "servant",
  "διδάσκαλος": "teacher",
  "δόλος": "deceit, guile",
  "δόξα": "glory",
  "δύναμαι": "to be able",
  "δύο": "two",
  "εἰ": "if",
  "εἰμί": "to be",
  "εἰς": "into, to",
  "εἷς": "one",
  "εὐθύνω": "to make straight",
  "εὑρίσκω": "to find",
  "ζητέω": "to seek",
  "ζωή": "life",
  "θέλημα": "will",
  "θέλω": "to wish, will",
  "θεάομαι": "to behold, gaze at",
  "θεός": "God",
  "καί": "and",
  "καθαρισμός": "purification",
  "καθώς": "just as",
  "καλέω": "to call",
  "καλός": "good, fine",
  "κατά": "according to, against",
  "καταβαίνω": "to come down",
  "καταλαμβάνω": "seized / grasped",
  "κεῖμαι": "to lie, be placed",
  "κράζω": "to cry out",
  "κόλπος": "bosom, side",
  "κόσμος": "world",
  "κύριος": "lord",
  "κἀγώ": "and I, I too",
  "λέγω": "to say",
  "λίθινος": "of stone",
  "λαλέω": "to speak",
  "λαμβάνω": "to take, receive",
  "λόγος": "word",
  "λύω": "to loose, untie",
  "μέγας": "great",
  "μένω": "to remain, abide",
  "μέσος": "middle, midst",
  "μήτηρ": "mother",
  "μαθητής": "disciple",
  "μαρτυρέω": "to bear witness",
  "μαρτυρία": "testimony",
  "μεθερμηνεύω": "to translate",
  "μεθύω": "to be drunk",
  "μετρητής": "measure (metretes)",
  "μονογενής": "only, only-begotten",
  "νυμφίος": "bridegroom",
  "νόμος": "law",
  "νῦν": "now",
  "οἶδα": "to know",
  "οἶνος": "wine",
  "οὐ": "not",
  "οὐδέ": "and not, nor",
  "οὐδείς": "no one",
  "οὐρανός": "heaven, sky",
  "οὔπω": "not yet",
  "οὖν": "therefore, then",
  "οὗτος": "this one",
  "πάλιν": "again",
  "πέμπω": "to send",
  "πέραν": "beyond, across",
  "παρά": "from, beside",
  "παραλαμβάνω": "to receive, take",
  "πατήρ": "father",
  "περί": "concerning, about",
  "περιπατέω": "to walk",
  "περιστερά": "dove",
  "πιστεύω": "to believe, trust",
  "πλήρης": "full",
  "πλήρωμα": "fullness",
  "πνεῦμα": "spirit, breath",
  "ποιέω": "to do, make",
  "πού": "somewhere",
  "ποῦ": "where?",
  "προφήτης": "prophet",
  "πρό": "before",
  "πρός": "to, toward, with",
  "πρῶτος": "first",
  "πόθεν": "from where",
  "πόλις": "city",
  "πώποτε": "ever, at any time",
  "πᾶς": "all, every",
  "σάρξ": "flesh",
  "σεαυτοῦ": "yourself",
  "σημεῖον": "sign",
  "σκηνόω": "to pitch a tent, dwell",
  "σκοτία": "darkness",
  "στήκω": "to stand",
  "στρέφω": "to turn",
  "συκῆ": "fig tree",
  "σύ": "you",
  "τέκνον": "child",
  "τίθημι": "to put, place",
  "τίς": "who? what?",
  "τηρέω": "to keep",
  "τρίτος": "third",
  "τρεῖς": "three",
  "τὶς": "someone, a certain",
  "υἱός": "son",
  "φέρω": "to carry, bring",
  "φαίνω": "shines",
  "φανερόω": "to reveal",
  "φημί": "to say",
  "φωνέω": "to call",
  "φωνή": "voice, sound",
  "φωτίζω": "to give light to",
  "φῶς": "light",
  "χάρις": "grace, favor",
  "χωρέω": "to hold, contain",
  "χωρίς": "apart from",
  "ἀγαθός": "good",
  "ἀδελφός": "brother",
  "ἀκολουθέω": "to follow",
  "ἀκούω": "to hear",
  "ἀλήθεια": "truth",
  "ἀληθινός": "true, genuine",
  "ἀληθῶς": "truly",
  "ἀλλά": "but",
  "ἀμήν": "amen, truly",
  "ἀμνός": "lamb",
  "ἀνά": "each, apiece",
  "ἀνήρ": "man, husband",
  "ἀναβαίνω": "to go up",
  "ἀνοίγω": "to open",
  "ἀντί": "instead of, for",
  "ἀντλέω": "to draw (water)",
  "ἀποκρίνομαι": "to answer",
  "ἀποστέλλω": "to send (out)",
  "ἀπό": "from",
  "ἀπόκρισις": "answer",
  "ἀρνέομαι": "to deny",
  "ἀρχή": "beginning",
  "ἀρχιτρίκλινος": "master of the feast",
  "ἁμαρτία": "sin",
  "ἄγγελος": "angel, messenger",
  "ἄγω": "to lead, bring",
  "ἄν": "(untranslatable particle)",
  "ἄνθρωπος": "human being",
  "ἄνω": "up, to the brim",
  "ἄξιος": "worthy",
  "ἄρτι": "now, just now",
  "ἅγιος": "holy",
  "Ἀνδρέας": "Andrew",
  "ἐγώ": "I",
  "ἐκ": "out of, from",
  "ἐκεῖ": "there",
  "ἐκεῖνος": "that one",
  "ἐλάσσων": "lesser, inferior",
  "ἐμβλέπω": "to look at",
  "ἐν": "in",
  "ἐξέρχομαι": "to go out",
  "ἐξηγέομαι": "to explain, make known",
  "ἐξουσία": "authority, right",
  "ἐπί": "upon, on",
  "ἐπαύριον": "the next day",
  "ἐρωτάω": "to ask",
  "ἑρμηνεύω": "to translate, interpret",
  "ἔμπροσθεν": "before, ahead of",
  "ἔρημος": "wilderness, desert",
  "ἔρχομαι": "to come, go",
  "ἔχω": "to have",
  "ἕξ": "six",
  "ἕως": "until",
  "ἡμέρα": "day",
  "ἤ": "or",
  "ἥκω": "to have come",
  "Ἠλίας": "Elijah",
  "Ἠσαΐας": "Isaiah",
  "ἱερεύς": "priest",
  "ἱμάς": "strap, thong",
  "ἴδιος": "one’s own",
  "ἵνα": "so that, in order that",
  "ἵστημι": "to stand",
  "Ἰησοῦς": "Jesus",
  "Ἰορδάνης": "Jordan",
  "Ἰουδαῖος": "Judean, Jew",
  "Ἰσραήλ": "Israel",
  "Ἰσραηλίτης": "Israelite",
  "Ἰωάννης": "John",
  "Ἰωσήφ": "Joseph",
  "Ἱεροσόλυμα": "Jerusalem",
  "ὀπίσω": "after, behind",
  "ὁ": "the",
  "ὁδός": "way, road",
  "ὁμολογέω": "to confess, acknowledge",
  "ὁράω": "to see",
  "ὄνομα": "name",
  "ὅπου": "where",
  "ὅς": "who, which",
  "ὅσος": "as many as",
  "ὅταν": "whenever",
  "ὅτε": "when",
  "ὅτι": "that, because",
  "ὑδρία": "water-jar",
  "ὑπέρ": "above, on behalf of",
  "ὑποκάτω": "under, beneath",
  "ὑπό": "under, by",
  "ὑπόδημα": "sandal",
  "ὑστερέω": "to lack, run short",
  "ὕδωρ": "water",
  "ὡς": "as, like",
  "ὥρα": "hour",
  "ῥαββί": "rabbi",
  "μετά": "with, after", "Καφαρναούμ": "Capernaum", "πολύς": "much, many", "ἐγγύς": "near",
  "πάσχα": "Passover", "ἱερός": "sacred; temple", "πωλέω": "to sell", "βοῦς": "ox, cattle",
  "πρόβατον": "sheep", "κερματιστής": "money-changer", "κάθημαι": "to sit", "φραγέλλιον": "whip",
  "σχοινίον": "cord, rope", "ἐκβάλλω": "to drive out", "τέ": "and, both", "κολλυβιστής": "money-changer",
  "ἐκχέω": "to pour out", "κέρμα": "coin", "τράπεζα": "table", "ἀνατρέπω": "to overturn",
  "ἐντεῦθεν": "from here", "μή": "not", "οἶκος": "house", "ἐμπόριον": "house of trade",
  "μιμνῄσκω": "to remember", "ζῆλος": "zeal", "κατεσθίω": "to consume, devour", "δείκνυμι": "to show",
  "ναός": "temple, sanctuary", "ἐγείρω": "to raise", "τεσσεράκοντα": "forty", "ἔτος": "year",
  "οἰκοδομέω": "to build", "σῶμα": "body", "νεκρός": "dead", "γραφή": "Scripture", "ἑορτή": "feast",
  "θεωρέω": "to observe, behold", "ἑαυτοῦ": "himself", "χρεία": "need", "γάρ": "for, because",
  // Chapter 3
  "Νικόδημος": "Nicodemus", "ἄρχων": "ruler", "νύξ": "night", "ἐάν": "if",
  "ἄνωθεν": "from above; again", "βασιλεία": "kingdom", "πῶς": "how", "γέρων": "old man",
  "κοιλία": "womb, belly", "δεύτερος": "second", "εἰσέρχομαι": "to enter", "θαυμάζω": "to marvel, be amazed",
  "δεῖ": "it is necessary, must", "πνέω": "to blow", "ὑπάγω": "to go, depart", "οὕτω": "thus, in this way",
  "ἐπίγειος": "earthly", "ἐπουράνιος": "heavenly", "ὑψόω": "to lift up, exalt", "ὄφις": "serpent",
  "αἰώνιος": "eternal", "ἀγαπάω": "to love", "ὥστε": "so that", "ἀπόλλυμι": "to perish, destroy",
  "κρίνω": "to judge, condemn", "σῴζω": "to save", "ἤδη": "already, now", "κρίσις": "judgment",
  "μᾶλλον": "rather, more", "σκότος": "darkness", "πονηρός": "evil, wicked", "ἔργον": "work, deed",
  "φαῦλος": "worthless, wicked", "πράσσω": "to do, practise", "μισέω": "to hate", "ἐλέγχω": "to expose, convict",
  "ἐργάζομαι": "to work, do", "γῆ": "earth, land", "διατρίβω": "to stay, remain", "Αἰνών": "Aenon",
  "Σαλείμ": "Salim", "παραγίνομαι": "to come, arrive", "βάλλω": "to throw, cast", "φυλακή": "prison, guard",
  "ζήτησις": "dispute, discussion", "νύμφη": "bride", "φίλος": "friend", "χαρά": "joy",
  "χαίρω": "to rejoice", "ἐμός": "my, mine", "πληρόω": "to fill, fulfil", "αὐξάνω": "to increase, grow",
  "ἐλαττόω": "to decrease, grow less", "ἐπάνω": "above, over", "σφραγίζω": "to seal, certify", "ἀληθής": "true",
  "ῥῆμα": "word, saying", "μέτρον": "measure", "χείρ": "hand", "ἀπειθέω": "to disobey, refuse to believe",
  "ὀργή": "wrath, anger",
  // Chapter 4
  "καίτοιγε": "although, and yet", "ἀφίημι": "to leave, let go", "Ἰουδαία": "Judea", "ἀπέρχομαι": "to go away",
  "διέρχομαι": "to pass through", "Σαμάρεια": "Samaria", "Συχάρ": "Sychar", "πλησίον": "near",
  "χωρίον": "plot of land, field", "Ἰακώβ": "Jacob", "πηγή": "spring, well", "κοπιάω": "to grow weary, toil",
  "ὁδοιπορία": "journey", "καθέζομαι": "to sit down", "ἕκτος": "sixth", "πίνω": "to drink",
  "τροφή": "food", "ἀγοράζω": "to buy", "Σαμαρῖτις": "Samaritan woman", "αἰτέω": "to ask, request",
  "συγχράομαι": "to associate with", "Σαμαρίτης": "Samaritan", "δωρεά": "gift", "ζάω": "to live",
  "οὔτε": "neither, nor", "ἄντλημα": "bucket", "φρέαρ": "well, cistern", "βαθύς": "deep",
  "θρέμμα": "livestock", "διψάω": "to thirst", "αἰών": "age; forever", "ἅλλομαι": "to leap, well up",
  "μηδέ": "nor, not even", "ἐνθάδε": "here", "καλῶς": "well, rightly", "πέντε": "five",
  "εἶπον": "to say (aor. of λέγω)", "ὄρος": "mountain", "προσκυνέω": "to worship, bow down", "τόπος": "place",
  "σωτηρία": "salvation", "προσκυνητής": "worshiper", "τοιοῦτος": "such", "ἀναγγέλλω": "to announce, declare",
  "ἅπας": "all, everything", "μέντοι": "however, yet", "δεῦτε": "come!", "μήτι": "(question expecting “no”)",
  "μεταξύ": "between; meanwhile", "ἐσθίω": "to eat", "βρῶσις": "food, eating", "ἀλλήλων": "one another",
  "βρῶμα": "food", "τελειόω": "to complete, finish", "ἔτι": "still, yet", "τετράμηνος": "four months",
  "θερισμός": "harvest", "ἐπαίρω": "to lift up", "ὀφθαλμός": "eye", "χώρα": "field, region",
  "λευκός": "white", "θερίζω": "to reap", "μισθός": "wages, reward", "συνάγω": "to gather",
  "καρπός": "fruit", "σπείρω": "to sow", "ὁμοῦ": "together", "ἄλλος": "other, another",
  "κόπος": "labor, toil", "οὐκέτι": "no longer", "σός": "your", "λαλιά": "speech, telling",
  "σωτήρ": "savior", "ἐκεῖθεν": "from there", "πατρίς": "hometown", "τιμή": "honor",
  "δέχομαι": "to receive, welcome", "Γαλιλαῖος": "Galilean", "βασιλικός": "royal official", "ἀσθενέω": "to be sick",
  "ἰάομαι": "to heal", "μέλλω": "to be about to", "ἀποθνῄσκω": "to die", "τέρας": "wonder, portent",
  "πρίν": "before", "παιδίον": "child", "πορεύομαι": "to go, proceed", "δοῦλος (II)": "servant, slave",
  "ὑπαντάω": "to meet", "παῖς": "boy, servant", "πυνθάνομαι": "to inquire, ask", "κομψότερον": "better (in health)",
  "ἐχθές": "yesterday", "ἕβδομος": "seventh", "πυρετός": "fever", "οἰκία": "household, house", "ὅλος": "whole, all",
  // Chapter 5
  "προβατικός": "of sheep (Sheep Gate)", "κολυμβήθρα": "pool", "ἐπιλέγω": "to call, name", "Ἑβραϊστί": "in Hebrew/Aramaic",
  "Βηθζαθά": "Bethzatha", "στοά": "colonnade, porch", "κατάκειμαι": "to lie down", "πλῆθος": "multitude, crowd",
  "τυφλός": "blind", "χωλός": "lame", "ξηρός": "withered, paralysed", "ἐκδέχομαι": "to wait for, expect",
  "κίνησις": "moving, stirring", "καιρός": "appointed time, season", "ταράσσω": "to stir up, trouble", "ἐμβαίνω": "to step in",
  "ταραχή": "stirring, disturbance", "ὑγιής": "well, whole, healthy", "δήποτε": "whatever", "κατέχω": "to hold fast, afflict",
  "νόσημα": "disease", "τριάκοντα": "thirty", "ὀκτώ": "eight", "ἀσθένεια": "weakness, illness",
  "χρόνος": "time", "κράβαττος": "mat, pallet", "εὐθέως": "at once, immediately", "σάββατον": "Sabbath",
  "θεραπεύω": "to heal, cure", "ἔξεστι(ν)": "it is lawful", "ἐκνεύω": "to withdraw, slip away", "ὄχλος": "crowd",
  "μηκέτι": "no longer, no more", "ἁμαρτάνω": "to sin", "χείρων": "worse", "διώκω": "to pursue, persecute",
  "ἀποκτείνω": "to kill", "μόνος": "only, alone", "ἴσος": "equal", "ὁμοίως": "likewise",
  "φιλέω": "to love, befriend", "ὥσπερ": "just as", "ζῳοποιέω": "to give life", "τιμάω": "to honour",
  "μεταβαίνω": "to pass over, cross", "θάνατος": "death", "μνημεῖον": "tomb", "ἐκπορεύομαι": "to come out",
  "ἀνάστασις": "resurrection", "ἐμαυτοῦ": "myself", "δίκαιος": "just, righteous", "λύχνος": "lamp",
  "καίω": "to burn, kindle", "ἀγαλλιάω": "to rejoice, exult", "εἶδος": "form, appearance", "ἐραυνάω": "to search",
  "δοκέω": "to think, suppose", "ἀγάπη": "love", "κατηγορέω": "to accuse", "ἐλπίζω": "to hope", "γράμμα": "writing, letter",
  // Chapter 6
  "θάλασσα": "sea", "Τιβεριάς": "Tiberias", "ἀνέρχομαι": "to go up", "ἄρτος": "bread, loaf",
  "πειράζω": "to test, tempt", "διακόσιοι": "two hundred", "δηνάριον": "denarius", "ἀρκέω": "to suffice",
  "ἕκαστος": "each", "βραχύς": "little, short", "παιδάριον": "little boy", "ὧδε": "here",
  "κρίθινος": "of barley", "ὀψάριον": "fish", "τοσοῦτος": "so many, so great", "ἀναπίπτω": "to recline, sit down",
  "χόρτος": "grass", "ἀριθμός": "number", "πεντακισχίλιοι": "five thousand", "εὐχαριστέω": "to give thanks",
  "διαδίδωμι": "to distribute", "ἀνάκειμαι": "to recline (at table)", "ἐμπίπλημι": "to fill, satisfy", "περισσεύω": "to be left over, abound",
  "κλάσμα": "fragment, piece", "δώδεκα": "twelve", "κόφινος": "basket", "βιβρώσκω": "to eat",
  "ἁρπάζω": "to seize, snatch", "ἀναχωρέω": "to withdraw", "ὄψιος": "evening, late", "πλοῖον": "boat",
  "ἄνεμος": "wind", "διεγείρω": "to stir up, arouse", "ἐλαύνω": "to row, drive", "στάδιον": "stadion (~185 m)",
  "εἴκοσι": "twenty", "φοβέω": "to fear", "πλοιάριον": "small boat", "συνεισέρχομαι": "to enter with",
  "πότε": "when", "χορτάζω": "to fill, satisfy", "μάννα": "manna", "πάντοτε": "always",
  "πεινάω": "to hunger", "ἔξω": "out, outside", "ἀνίστημι": "to raise up", "ἔσχατος": "last",
  "γογγύζω": "to grumble, murmur", "ἕλκω": "to draw, drag", "διδακτός": "taught", "μανθάνω": "to learn",
  "μάχομαι": "to fight, quarrel", "τρώγω": "to gnaw, chew, eat", "πόσις": "drink", "κἀκεῖνος": "and he, that one also",
  "συναγωγή": "synagogue", "διδάσκω": "to teach", "σκληρός": "hard, harsh", "σκανδαλίζω": "to offend, cause to stumble",
  "πρότερος": "former, before", "ὠφελέω": "to profit, help", "παραδίδωμι": "to hand over, betray", "ἐκλέγω": "to choose",
  "διάβολος": "devil, slanderer", "Ἰούδας": "Judas", "Ἰσκαριώθ": "Iscariot",
  // Chapter 7
  "σκηνοπηγία": "Feast of Tabernacles", "κρυπτός": "hidden, secret", "παρρησία": "openness, boldness", "πάρειμι": "to be present, have come",
  "ὑμέτερος": "your", "ἕτοιμος": "ready", "τότε": "then", "φανερῶς": "openly",
  "γογγυσμός": "muttering, murmuring", "μέν": "on the one hand", "πλανάω": "to lead astray, deceive", "φόβος": "fear",
  "μεσόω": "to be in the middle", "διδαχή": "teaching", "πότερον": "whether", "ἀδικία": "unrighteousness, falsehood",
  "δαιμόνιον": "demon", "περιτομή": "circumcision", "περιτέμνω": "to circumcise", "χολάω": "to be angry",
  "ὄψις": "appearance, face", "Ἱεροσολυμίτης": "a person of Jerusalem", "πιάζω": "to seize, arrest", "ἐπιβάλλω": "to lay on",
  "ἀρχιερεύς": "chief priest", "ὑπηρέτης": "officer, attendant", "μικρός": "little, small", "διασπορά": "Dispersion, Diaspora",
  "Ἕλλην": "Greek", "ποταμός": "river", "ῥέω": "to flow", "οὐδέπω": "not yet",
  "δοξάζω": "to glorify", "σπέρμα": "seed, offspring", "Δαυίδ": "David", "Βηθλέεμ": "Bethlehem",
  "κώμη": "village", "σχίσμα": "division, split", "οὐδέποτε": "never", "ἐπάρατος": "accursed",
};
