// English glosses by lemma. Extend when a new chapter adds vocabulary.
export const GLOSS_EN = {
  "Βηθανία": "Bethany",
  "Βηθσαϊδά": "Bethsaida",
  "Γαλιλαία": "Galilee",
  "Κανά": "Cana",
  "Κηφᾶς": "Cephas",
  "Λευίτης": "Levite",
  "Μεσσίας": "Messiah",
  "Μωϋσῆς": "Moses",
  "Ναζαρά": "Nazareth",
  "Ναθαναήλ": "Nathanael",
  "Πέτρος": "Peter",
  "Σίμων": "Simon",
  "Φίλιππος": "Philip",
  "Φαρισαῖος": "Pharisee",
  "Χριστός": "Christ, Anointed",
  "αἴρω": "to take away, lift up",
  "αἷμα": "blood",
  "αὐτός": "he, it, same",
  "βαπτίζω": "to baptize",
  "βασιλεύς": "king",
  "βλέπω": "to see, look",
  "βοάω": "to cry out",
  "γάμος": "wedding",
  "γίνομαι": "to become, come to be",
  "γεμίζω": "to fill",
  "γεννάω": "to beget, give birth",
  "γεύομαι": "to taste",
  "γινώσκω": "to know",
  "γράφω": "to write",
  "γυνή": "woman",
  "δέ": "but, and",
  "δέκατος": "tenth",
  "δίδωμι": "to give",
  "διά": "through, on account of",
  "διάκονος": "servant",
  "διδάσκαλος": "teacher",
  "δόλος": "deceit, guile",
  "δόξα": "glory",
  "δύναμαι": "to be able",
  "δύο": "two",
  "εἰ": "if",
  "εἰμί": "to be",
  "εἰς": "into, to",
  "εἷς": "one",
  "εὐθύνω": "to make straight",
  "εὑρίσκω": "to find",
  "ζητέω": "to seek",
  "ζωή": "life",
  "θέλημα": "will",
  "θέλω": "to wish, will",
  "θεάομαι": "to behold, gaze at",
  "θεός": "God",
  "καί": "and",
  "καθαρισμός": "purification",
  "καθώς": "just as",
  "καλέω": "to call",
  "καλός": "good, fine",
  "κατά": "according to, against",
  "καταβαίνω": "to come down",
  "καταλαμβάνω": "seized / grasped",
  "κεῖμαι": "to lie, be placed",
  "κράζω": "to cry out",
  "κόλπος": "bosom, side",
  "κόσμος": "world",
  "κύριος": "lord",
  "κἀγώ": "and I, I too",
  "λέγω": "to say",
  "λίθινος": "of stone",
  "λαλέω": "to speak",
  "λαμβάνω": "to take, receive",
  "λόγος": "word",
  "λύω": "to loose, untie",
  "μέγας": "great",
  "μένω": "to remain, abide",
  "μέσος": "middle, midst",
  "μήτηρ": "mother",
  "μαθητής": "disciple",
  "μαρτυρέω": "to bear witness",
  "μαρτυρία": "testimony",
  "μεθερμηνεύω": "to translate",
  "μεθύω": "to be drunk",
  "μετρητής": "measure (metretes)",
  "μονογενής": "only, only-begotten",
  "νυμφίος": "bridegroom",
  "νόμος": "law",
  "νῦν": "now",
  "οἶδα": "to know",
  "οἶνος": "wine",
  "οὐ": "not",
  "οὐδέ": "and not, nor",
  "οὐδείς": "no one",
  "οὐρανός": "heaven, sky",
  "οὔπω": "not yet",
  "οὖν": "therefore, then",
  "οὗτος": "this one",
  "πάλιν": "again",
  "πέμπω": "to send",
  "πέραν": "beyond, across",
  "παρά": "from, beside",
  "παραλαμβάνω": "to receive, take",
  "πατήρ": "father",
  "περί": "concerning, about",
  "περιπατέω": "to walk",
  "περιστερά": "dove",
  "πιστεύω": "to believe, trust",
  "πλήρης": "full",
  "πλήρωμα": "fullness",
  "πνεῦμα": "spirit, breath",
  "ποιέω": "to do, make",
  "πού": "somewhere",
  "ποῦ": "where?",
  "προφήτης": "prophet",
  "πρό": "before",
  "πρός": "to, toward, with",
  "πρῶτος": "first",
  "πόθεν": "from where",
  "πόλις": "city",
  "πώποτε": "ever, at any time",
  "πᾶς": "all, every",
  "σάρξ": "flesh",
  "σεαυτοῦ": "yourself",
  "σημεῖον": "sign",
  "σκηνόω": "to pitch a tent, dwell",
  "σκοτία": "darkness",
  "στήκω": "to stand",
  "στρέφω": "to turn",
  "συκῆ": "fig tree",
  "σύ": "you",
  "τέκνον": "child",
  "τίθημι": "to put, place",
  "τίς": "who? what?",
  "τηρέω": "to keep",
  "τρίτος": "third",
  "τρεῖς": "three",
  "τὶς": "someone, a certain",
  "υἱός": "son",
  "φέρω": "to carry, bring",
  "φαίνω": "shines",
  "φανερόω": "to reveal",
  "φημί": "to say",
  "φωνέω": "to call",
  "φωνή": "voice, sound",
  "φωτίζω": "to give light to",
  "φῶς": "light",
  "χάρις": "grace, favor",
  "χωρέω": "to hold, contain",
  "χωρίς": "apart from",
  "ἀγαθός": "good",
  "ἀδελφός": "brother",
  "ἀκολουθέω": "to follow",
  "ἀκούω": "to hear",
  "ἀλήθεια": "truth",
  "ἀληθινός": "true, genuine",
  "ἀληθῶς": "truly",
  "ἀλλά": "but",
  "ἀμήν": "amen, truly",
  "ἀμνός": "lamb",
  "ἀνά": "each, apiece",
  "ἀνήρ": "man, husband",
  "ἀναβαίνω": "to go up",
  "ἀνοίγω": "to open",
  "ἀντί": "instead of, for",
  "ἀντλέω": "to draw (water)",
  "ἀποκρίνομαι": "to answer",
  "ἀποστέλλω": "to send (out)",
  "ἀπό": "from",
  "ἀπόκρισις": "answer",
  "ἀρνέομαι": "to deny",
  "ἀρχή": "beginning",
  "ἀρχιτρίκλινος": "master of the feast",
  "ἁμαρτία": "sin",
  "ἄγγελος": "angel, messenger",
  "ἄγω": "to lead, bring",
  "ἄν": "(untranslatable particle)",
  "ἄνθρωπος": "human being",
  "ἄνω": "up, to the brim",
  "ἄξιος": "worthy",
  "ἄρτι": "now, just now",
  "ἅγιος": "holy",
  "Ἀνδρέας": "Andrew",
  "ἐγώ": "I",
  "ἐκ": "out of, from",
  "ἐκεῖ": "there",
  "ἐκεῖνος": "that one",
  "ἐλάσσων": "lesser, inferior",
  "ἐμβλέπω": "to look at",
  "ἐν": "in",
  "ἐξέρχομαι": "to go out",
  "ἐξηγέομαι": "to explain, make known",
  "ἐξουσία": "authority, right",
  "ἐπί": "upon, on",
  "ἐπαύριον": "the next day",
  "ἐρωτάω": "to ask",
  "ἑρμηνεύω": "to translate, interpret",
  "ἔμπροσθεν": "before, ahead of",
  "ἔρημος": "wilderness, desert",
  "ἔρχομαι": "to come, go",
  "ἔχω": "to have",
  "ἕξ": "six",
  "ἕως": "until",
  "ἡμέρα": "day",
  "ἤ": "or",
  "ἥκω": "to have come",
  "Ἠλίας": "Elijah",
  "Ἠσαΐας": "Isaiah",
  "ἱερεύς": "priest",
  "ἱμάς": "strap, thong",
  "ἴδιος": "one’s own",
  "ἵνα": "so that, in order that",
  "ἵστημι": "to stand",
  "Ἰησοῦς": "Jesus",
  "Ἰορδάνης": "Jordan",
  "Ἰουδαῖος": "Judean, Jew",
  "Ἰσραήλ": "Israel",
  "Ἰσραηλίτης": "Israelite",
  "Ἰωάννης": "John",
  "Ἰωσήφ": "Joseph",
  "Ἱεροσόλυμα": "Jerusalem",
  "ὀπίσω": "after, behind",
  "ὁ": "the",
  "ὁδός": "way, road",
  "ὁμολογέω": "to confess, acknowledge",
  "ὁράω": "to see",
  "ὄνομα": "name",
  "ὅπου": "where",
  "ὅς": "who, which",
  "ὅσος": "as many as",
  "ὅταν": "whenever",
  "ὅτε": "when",
  "ὅτι": "that, because",
  "ὑδρία": "water-jar",
  "ὑπέρ": "above, on behalf of",
  "ὑποκάτω": "under, beneath",
  "ὑπό": "under, by",
  "ὑπόδημα": "sandal",
  "ὑστερέω": "to lack, run short",
  "ὕδωρ": "water",
  "ὡς": "as, like",
  "ὥρα": "hour",
  "ῥαββί": "rabbi",
  "μετά": "with, after", "Καφαρναούμ": "Capernaum", "πολύς": "much, many", "ἐγγύς": "near",
  "πάσχα": "Passover", "ἱερός": "sacred; temple", "πωλέω": "to sell", "βοῦς": "ox, cattle",
  "πρόβατον": "sheep", "κερματιστής": "money-changer", "κάθημαι": "to sit", "φραγέλλιον": "whip",
  "σχοινίον": "cord, rope", "ἐκβάλλω": "to drive out", "τέ": "and, both", "κολλυβιστής": "money-changer",
  "ἐκχέω": "to pour out", "κέρμα": "coin", "τράπεζα": "table", "ἀνατρέπω": "to overturn",
  "ἐντεῦθεν": "from here", "μή": "not", "οἶκος": "house", "ἐμπόριον": "house of trade",
  "μιμνῄσκω": "to remember", "ζῆλος": "zeal", "κατεσθίω": "to consume, devour", "δείκνυμι": "to show",
  "ναός": "temple, sanctuary", "ἐγείρω": "to raise", "τεσσεράκοντα": "forty", "ἔτος": "year",
  "οἰκοδομέω": "to build", "σῶμα": "body", "νεκρός": "dead", "γραφή": "Scripture", "ἑορτή": "feast",
  "θεωρέω": "to observe, behold", "ἑαυτοῦ": "himself", "χρεία": "need", "γάρ": "for, because",
};
