import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chapterGreek } from './lib/greek.mjs';

// Regenerates src/data/john<N>.ts (base = English full Chapter) and
// src/data/john<N>.<lang>.ts (overlays) from scripts/content/*.mjs + the Greek
// source. Run with:  npm run build:data
//
// ── Adding a chapter ──   author scripts/content/john<N>.<lang>.mjs for each
//                         language, add an entry to CHAPTERS below, run build.
// ── Adding a language ──  for every chapter add scripts/content/john<N>.<L>.mjs,
//                         list L in LANGS, add a src/data/lexicon.<L>.ts (for the
//                         inspector) + a UI block in src/data/ui.ts, then wire it
//                         into src/App.tsx (BOOK/imports). Run build.

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.join(__dirname, '../src/data');

// 'en' is the base language (emits the full Chapter). Others emit overlays.
const LANGS = ['en', 'sv'];

const CHAPTERS = [
  { num: 1, titles: { en: 'The Prologue & the First Witnesses', sv: 'Prologen och de första vittnena' } },
  { num: 2, titles: { en: 'The Wedding at Cana', sv: 'Bröllopet i Kana' } },
];

const cap = (s) => s[0].toUpperCase() + s.slice(1);
const TRAIL = /['’”".,;:!?—]+$/u;

function emitEnglish(ch, v, entries) {
  return entries.map(([text, align, supplied], i) => {
    let core = text, after = '';
    const mm = core.match(TRAIL);
    if (mm && mm.index > 0) { after = mm[0]; core = core.slice(0, mm.index); }
    const ids = (align || '').trim() ? align.trim().split(/\s+/) : [];
    const parts = [`id: 'e${ch}.${v}.${i + 1}'`, `text: ${JSON.stringify(core)}`];
    if (after) parts.push(`after: ${JSON.stringify(after)}`);
    parts.push(`align: [${ids.map((x) => `'${x}'`).join(', ')}]`);
    if (supplied) parts.push('supplied: true');
    return `        { ${parts.join(', ')} },`;
  }).join('\n');
}
function emitAnnotations(ch, v, notes) {
  return notes.map((n, i) => {
    const refs = n.refs.trim().split(/\s+/).map((x) => `'${x}'`).join(', ');
    return [
      `        {`, `          id: 'a${ch}.${v}.${i + 1}',`,
      `          kind: ${JSON.stringify(n.kind)},`, `          refs: [${refs}],`,
      `          lemma: ${JSON.stringify(n.lemma)},`, `          title: ${JSON.stringify(n.title)},`,
      `          body: ${JSON.stringify(n.body)},`, `        },`,
    ].join('\n');
  }).join('\n');
}
function emitGreek(tokens) {
  return tokens.map((t) => {
    const parts = [`id: '${t.id}'`, `text: ${JSON.stringify(t.text)}`];
    if (t.after) parts.push(`after: ${JSON.stringify(t.after)}`);
    parts.push(`lemma: ${JSON.stringify(t.lemma)}`, `translit: ${JSON.stringify(t.translit)}`, `morph: ${JSON.stringify(t.morph)}`);
    if (t.gloss) parts.push(`gloss: ${JSON.stringify(t.gloss)}`);
    return `        { ${parts.join(', ')} },`;
  }).join('\n');
}

async function loadContent(chNum, lang) {
  const file = path.join(__dirname, 'content', `john${chNum}.${lang}.mjs`);
  if (!fs.existsSync(file)) return null;
  const mod = await import(`${file}?t=${Date.now()}`);
  return mod.CONTENT;
}

let brokenTotal = 0;
function validate(chNum, greek, content) {
  const ids = new Set(Object.values(greek).flat().map((t) => t.id));
  let broken = 0;
  for (const [v, c] of Object.entries(content)) {
    for (const [, align] of c.english) for (const id of (align || '').trim().split(/\s+/).filter(Boolean)) if (!ids.has(id)) { broken++; console.error(`  ✗ ${chNum}:${v} english → ${id}`); }
    for (const n of c.annotations) for (const id of n.refs.trim().split(/\s+/).filter(Boolean)) if (!ids.has(id)) { broken++; console.error(`  ✗ ${chNum}:${v} note → ${id}`); }
  }
  brokenTotal += broken;
  return broken;
}

for (const chap of CHAPTERS) {
  const ch = chap.num;
  const en = await loadContent(ch, 'en');
  if (!en) throw new Error(`missing base content: john${ch}.en.mjs`);
  const verseNums = Object.keys(en).map(Number).sort((a, b) => a - b);
  const greek = chapterGreek(ch, verseNums);
  validate(ch, greek, en);

  // Base chapter (English).
  let verses = '';
  for (const v of verseNums) {
    if (!en[v]) throw new Error(`john${ch}.en.mjs missing verse ${v}`);
    verses += `    {\n      ref: '${ch}:${v}',\n      chapter: ${ch},\n      verse: ${v},\n`;
    verses += `      greek: [\n${emitGreek(greek[v])}\n      ],\n`;
    verses += `      english: [\n${emitEnglish(ch, v, en[v].english)}\n      ],\n`;
    verses += `      annotations: [\n${emitAnnotations(ch, v, en[v].annotations)}\n      ],\n`;
    verses += `    },\n`;
  }
  let base = "import type { Chapter } from './types';\n\n";
  base += `// The Gospel of John, chapter ${ch}. Greek: Nestle 1904 (public domain).\n`;
  base += '// Translation & annotations: this edition. GENERATED by scripts/build.mjs\n';
  base += `// from scripts/content/john${ch}.en.mjs — edit there, not here.\n\n`;
  base += `export const john${ch}: Chapter = {\n  book: 'John',\n  chapter: ${ch},\n  title: ${JSON.stringify(chap.titles.en)},\n  verses: [\n${verses}  ],\n};\n`;
  fs.writeFileSync(path.join(DATA, `john${ch}.ts`), base);

  // Overlays (other languages).
  for (const lang of LANGS) {
    if (lang === 'en') continue;
    const content = await loadContent(ch, lang);
    if (!content) continue;
    validate(ch, greek, content);
    let overlay = '';
    for (const v of verseNums) {
      if (!content[v]) continue;
      overlay += `  ${v}: {\n    english: [\n${emitEnglish(ch, v, content[v].english)}\n    ],\n    annotations: [\n${emitAnnotations(ch, v, content[v].annotations)}\n    ],\n  },\n`;
    }
    const name = `john${ch}`;
    const exportName = `${name}${cap(lang)}`;
    let sv = `import { ${name} } from './${name}';\n`;
    sv += "import type { Annotation, Chapter, EnglishToken } from './types';\n\n";
    sv += `// ${lang} edition of John ${ch}. Shares ${name}’s Greek spine; only the\n`;
    sv += `// translation and annotations differ. GENERATED by scripts/build.mjs\n`;
    sv += `// from scripts/content/john${ch}.${lang}.mjs — edit there, not here.\n\n`;
    sv += `const OVERLAY: Record<number, { english: EnglishToken[]; annotations: Annotation[] }> = {\n${overlay}};\n\n`;
    sv += `export const ${exportName}: Chapter = {\n  ...${name},\n  title: ${JSON.stringify(chap.titles[lang])},\n`;
    sv += `  verses: ${name}.verses.map((v) => ({\n    ...v,\n    english: OVERLAY[v.verse]?.english ?? v.english,\n    annotations: OVERLAY[v.verse]?.annotations ?? v.annotations,\n  })),\n};\n`;
    fs.writeFileSync(path.join(DATA, `john${ch}.${lang}.ts`), sv);
  }
  console.log(`✓ John ${ch}: ${verseNums.length} verses, langs [${LANGS.join(', ')}]`);
}

if (brokenTotal) { console.error(`\n${brokenTotal} broken alignment reference(s).`); process.exit(1); }
console.log('\nAll alignment references valid. Wrote src/data/john*.ts');
